KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/experimental/avm.f File Reference
avm.f File Reference
Functions/Subroutines
real function avm_vdiff (ix, iy, iz, e, c1, ncut)
real function deltaf (ix, iy, iz, iel)
Function/Subroutine Documentation
avm_vdiff()
real function avm_vdiff (integer ix, integer iy, integer iz, integer e, real c1, integer ncut)
Definition at line 1 of file avm.f.
References build_hpf_fld(), build_hpf_mat(), cfill(), convop(), copy(), deltaf(), dsop(), exitt(), gl2norm(), glamax(), glamin(), glsc2(), hpf_trns_fcn(), map_c_to_f_h1_bilin(), sub2(), and vlmax().
deltaf()
real function deltaf (ix, iy, iz, iel)
Definition at line 135 of file avm.f.
References cfill(), and dxmin_e().