KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/bdry.f File Reference
bdry.f File Reference
Functions/Subroutines
subroutine setlog (ifecho)
subroutine setrzer
subroutine chknord (IFALGN, IFNORX, IFNORY, IFNORZ, IFC, IEL)
subroutine chkaxcb
subroutine chkcbc (CB, IEL, IFC, IFALGN, IERR)
subroutine bcmask
subroutine bcdirvc (V1, V2, V3, mask1, mask2, mask3)
subroutine bcdirsc (S)
subroutine bcneusc (S, ITYPE)
subroutine faceis (CB, S, IEL, IFACE, NX, NY, NZ)
subroutine faceiv (CB, V1, V2, V3, IEL, IFACE, NX, NY, NZ)
subroutine nekasgn (ix, iy, iz, e)
subroutine bcneutr
subroutine trcon (TRX, TRY, TRZ, TR1, TR2, TR3, IEL, IFC)
subroutine trst2d (TRX, TRY, SIGST, IEL, IFC)
subroutine trstax (TRX, TRY, SIGST, IEL, IFC)
subroutine ctang2d (CANG, SANG, IXN, IYN, IAN, IFC, IEL)
subroutine trst3d (TRX, TRY, TRZ, SIGST, IEL, IFC)
subroutine setdrs (DRM1, DRTM1, DSM1, DSTM1, IFC)
subroutine globrot (R1, R2, R3, IEL, IFC)
subroutine facec2 (A1, A2, B1, B2, IFC)
subroutine lfalse (IFA, N)
subroutine rzero3 (A, B, C, N)
subroutine unitvec (X, Y, Z, N)
subroutine chkzvn (VMAX, IEL, IFC, IVNORL)
subroutine bctwall (TMP1, TMP2, TMP3)
subroutine antimsk1 (X, XMASK, N)
subroutine check_cyclic
real function glcflux (tx, ty, tz)
subroutine local_bflux (flux, tx, ty, tz, ifld)
subroutine facind2 (JS1, JF1, JSKIP1, JS2, JF2, JSKIP2, IFC)
subroutine create_obj (iobjo, sid_list, n)
subroutine setbc (bid, ifld, cbci)
Function/Subroutine Documentation
antimsk1()
subroutine antimsk1 (real, dimension(1) X, real, dimension(1) XMASK, N)
Definition at line 1923 of file bdry.f.
bcdirsc()
subroutine bcdirsc (dimension(lx1,ly1,lz1,lelt) S)
Definition at line 709 of file bdry.f.
References add2(), col2(), dnekclock(), dsop(), faceis(), facev(), and rzero().
bcdirvc()
subroutine bcdirvc (real, dimension(lx1,ly1,lz1,lelv) V1, real, dimension(lx1,ly1,lz1,lelv) V2, real, dimension(lx1,ly1,lz1,lelv) V3, real, dimension(lx1,ly1,lz1,lelv) mask1, real, dimension(lx1,ly1,lz1,lelv) mask2, real, dimension(lx1,ly1,lz1,lelv) mask3)
Definition at line 573 of file bdry.f.
References add2(), antimsk1(), col2(), dnekclock(), faceiv(), facev(), fix_surface_flux(), globrot(), opdsop(), rmask(), and rzero().
bcmask()
subroutine bcmask
Definition at line 315 of file bdry.f.
References chknord(), dsop(), facev(), opdsop(), rone(), rzero(), and stsmask().
bcneusc()
subroutine bcneusc (dimension(lx1,ly1,lz1,lelt) S, ITYPE)
Definition at line 785 of file bdry.f.
References dnekclock(), facind(), nekasgn(), and rzero().
bcneutr()
subroutine bcneutr
Definition at line 1199 of file bdry.f.
References add2(), cfill(), faccvs(), faceis(), faceiv(), facexs(), globrot(), rzero3(), trcon(), trst2d(), trst3d(), and trstax().
bctwall()
subroutine bctwall (dimension(lx1,ly1,lz1,1) TMP1, dimension(lx1,ly1,lz1,1) TMP2, dimension(lx1,ly1,lz1,1) TMP3)
Definition at line 1871 of file bdry.f.
References faceiv(), facev(), globrot(), and rzero().
check_cyclic()
subroutine check_cyclic
Definition at line 1938 of file bdry.f.
References facind2(), facindr(), iglmax(), opdssum(), and rzero().
chkaxcb()
subroutine chkaxcb
Definition at line 251 of file bdry.f.
References exitt().
chkcbc()
subroutine chkcbc (character CB, IEL, IFC, logical IFALGN, IERR)
Definition at line 274 of file bdry.f.
chknord()
subroutine chknord (logical IFALGN, logical IFNORX, logical IFNORY, logical IFNORZ, IFC, IEL)
Definition at line 184 of file bdry.f.
chkzvn()
subroutine chkzvn (VMAX, IEL, IFC, IVNORL)
Definition at line 1843 of file bdry.f.
References facdot().
create_obj()
subroutine create_obj (iobjo, integer, dimension(n) sid_list, n)
Definition at line 2114 of file bdry.f.
References exitti().
ctang2d()
subroutine ctang2d (dimension(2) CANG, dimension(2) SANG, dimension(2) IXN, dimension(2) IYN, dimension(2) IAN, IFC, IEL)
Definition at line 1529 of file bdry.f.
References dot().
facec2()
subroutine facec2 (dimension(lx1) A1, dimension(lx1) A2, dimension(lx1,ly1) B1, dimension(lx1,ly1) B2, IFC)
Definition at line 1781 of file bdry.f.
faceis()
subroutine faceis (character CB, dimension(lx1,ly1,lz1) S, IEL, IFACE, NX, NY, NZ)
Definition at line 918 of file bdry.f.
References facind(), and nekasgn().
faceiv()
subroutine faceiv (character CB, dimension(nx,ny,nz) V1, dimension(nx,ny,nz) V2, dimension(nx,ny,nz) V3, IEL, IFACE, NX, NY, NZ)
Definition at line 1001 of file bdry.f.
References chcopy(), facind(), and nekasgn().
facind2()
subroutine facind2 (JS1, JF1, JSKIP1, JS2, JF2, JSKIP2, IFC)
Definition at line 2097 of file bdry.f.
References dsset().
glcflux()
real function glcflux (real, dimension(lx1,ly1,lz1,lelv) tx, real, dimension(lx1,ly1,lz1,lelv) ty, real, dimension(lx1,ly1,lz1,lelv) tz)
Definition at line 2014 of file bdry.f.
References facind(), and glsum().
globrot()
subroutine globrot (dimension(lx1,ly1,lz1) R1, dimension(lx1,ly1,lz1) R2, dimension(lx1,ly1,lz1) R3, IEL, IFC)
Definition at line 1721 of file bdry.f.
References dsset().
lfalse()
subroutine lfalse (logical, dimension(1) IFA, N)
Definition at line 1812 of file bdry.f.
local_bflux()
subroutine local_bflux (real, dimension(lx1,ly1,lz1,1) flux, real, dimension(lx1,ly1,lz1,1) tx, real, dimension(lx1,ly1,lz1,1) ty, real, dimension(lx1,ly1,lz1,1) tz, ifld)
Definition at line 2056 of file bdry.f.
References facind(), and rzero().
nekasgn()
subroutine nekasgn (ix, iy, iz, integer e)
Definition at line 1120 of file bdry.f.
rzero3()
subroutine rzero3 (dimension(1) A, dimension(1) B, dimension(1) C, N)
Definition at line 1820 of file bdry.f.
setbc()
subroutine setbc (integer bid, ifld, character*3 cbci)
Definition at line 2152 of file bdry.f.
References exitti().
setdrs()
subroutine setdrs (dimension(lx1,lx1) DRM1, dimension(lx1,lx1) DRTM1, dimension(ly1,ly1) DSM1, dimension(ly1,ly1) DSTM1, IFC)
Definition at line 1691 of file bdry.f.
References copy().
setlog()
subroutine setlog (logical ifecho)
Definition at line 2 of file bdry.f.
References chkcbc(), chknord(), exitt(), gllog(), iglsum(), lfalse(), and set_ifbcor().
setrzer()
subroutine setrzer
Definition at line 144 of file bdry.f.
trcon()
subroutine trcon (dimension(lx1,ly1,lz1) TRX, dimension(lx1,ly1,lz1) TRY, dimension(lx1,ly1,lz1) TRZ, TR1, TR2, TR3, IEL, IFC)
Definition at line 1303 of file bdry.f.
References dsset().
trst2d()
subroutine trst2d (dimension(lx1,ly1,lz1) TRX, dimension(lx1,ly1,lz1) TRY, dimension(lx1,1) SIGST, IEL, IFC)
Definition at line 1343 of file bdry.f.
References chsign(), ctang2d(), dsset(), and mxm().
trst3d()
subroutine trst3d (dimension(lx1,ly1,lz1) TRX, dimension(lx1,ly1,lz1) TRY, dimension(lx1,ly1,lz1) TRZ, dimension(lx1,ly1) SIGST, IEL, IFC)
Definition at line 1590 of file bdry.f.
References add2(), exitt(), facexv(), facsub2(), mxm(), rzero3(), and setdrs().
trstax()
subroutine trstax (dimension(lx1,ly1,lz1) TRX, dimension(lx1,ly1,lz1) TRY, dimension(lx1,ly1) SIGST, IEL, IFC)
Definition at line 1408 of file bdry.f.
References col2(), ctang2d(), dsset(), facec2(), and mxm().
unitvec()
subroutine unitvec (dimension(1) X, dimension(1) Y, dimension(1) Z, N)
Definition at line 1830 of file bdry.f.