KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/connect2.f File Reference
connect2.f File Reference
Functions/Subroutines
subroutine readat
subroutine vrdsmsh
subroutine vrdsmshx
subroutine rotat2 (xyz, angle, npts)
subroutine scale (xyzl, nl)
subroutine inrtia (xyzi, cg, xyzl, n, itype)
subroutine volume2 (vol, xyz, n)
subroutine findcg (cg, xyz, n)
subroutine divide (list1, list2, nl1, nl2, ifok, list, nl, xyzi, cg, WGT)
subroutine bufchk (buf, n)
subroutine chk_xyz
subroutine chk_nel
subroutine cscan (sout, key, nk)
Function/Subroutine Documentation
bufchk()
subroutine bufchk (real, dimension(n) buf, integer n)
Definition at line 911 of file connect2.f.
chk_nel()
subroutine chk_nel
Definition at line 934 of file connect2.f.
References exitt(), and iglmax().
chk_xyz()
subroutine chk_xyz
Definition at line 920 of file connect2.f.
cscan()
subroutine cscan (character*132 sout, character*132 key, nk)
Definition at line 984 of file connect2.f.
References blank(), chcopy(), and indx1().
divide()
subroutine divide (dimension(lelt) list1, dimension(lelt) list2, nl1, nl2, logical ifok, dimension(lelt) list, nl, dimension(3) xyzi, dimension(3,lelt) cg, dimension(1) WGT)
Definition at line 768 of file connect2.f.
References col2(), fmdian(), and igop().
findcg()
subroutine findcg (dimension(3,1) cg, dimension(3,8,1) xyz, n)
Definition at line 748 of file connect2.f.
References cmult(), and rzero().
inrtia()
subroutine inrtia (dimension(3) xyzi, dimension(3) cg, dimension(3,1) xyzl, n, itype)
Definition at line 648 of file connect2.f.
References gop().
readat()
subroutine readat
Definition at line 2 of file connect2.f.
References bcast(), chk_nel(), cscan(), dnekclock(), dnekclock_sync(), echopar(), exitti(), flush_io(), izero(), mapelpr(), nekgsync(), rdbdry(), rdcurve(), rdhist(), rdicdf(), rdmatp(), rdmesh(), rdobj(), rdout(), rdparam(), read_re2_data(), read_re2_hdr(), and readat_par().
rotat2()
subroutine rotat2 (dimension(3,1) xyz, angle, npts)
Definition at line 554 of file connect2.f.
References copy(), mod1(), mxm(), and rzero().
scale()
subroutine scale (dimension(3,8,lelt) xyzl, nl)
Definition at line 601 of file connect2.f.
References glsum(), gop(), inrtia(), rzero(), and volume2().
volume2()
subroutine volume2 (dimension(1) vol, dimension(3,2,2,2,1) xyz, n)
Definition at line 697 of file connect2.f.
vrdsmsh()
subroutine vrdsmsh
Definition at line 138 of file connect2.f.
References col2(), copy(), dsop(), dssum(), exitt(), facev(), glmax(), glmin(), gop(), iglsum(), qmask(), rone(), sub2(), vlmax(), and vlmin().
vrdsmshx()
subroutine vrdsmshx
Definition at line 368 of file connect2.f.
References col2(), copy(), dsop(), dssum(), facev(), glmax(), glmin(), qmask(), rone(), sub2(), vlmax(), and vlmin().