KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/convect2.f File Reference
convect2.f File Reference
Functions/Subroutines
subroutine setup_convect (igeom)
subroutine set_char_mask (mask, u, v, w)
subroutine set_dealias_rx
Function/Subroutine Documentation
set_char_mask()
subroutine set_char_mask (real, dimension(lxyz1,1) mask, real, dimension(lxyz1,1) u, real, dimension(lxyz1,1) v, real, dimension(lxyz1,1) w)
Definition at line 75 of file convect2.f.
References dsop(), faccl3(), facev(), faddcl3(), fcaver(), rone(), and rzero().
set_dealias_rx()
subroutine set_dealias_rx
Definition at line 120 of file convect2.f.
References intp_rstd(), and zwgl().
setup_convect()
subroutine setup_convect (igeom)
Definition at line 16 of file convect2.f.
References exitti(), opsub3(), rone(), rzero(), set_bdivw(), set_binv(), set_bmass(), set_conv_char(), set_convect_cons(), and set_convect_new().