KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dbdsqr.f File Reference
dbdsqr.f File Reference
Functions/Subroutines
subroutine dbdsqr (UPLO, N, NCVT, NRU, NCC, D, E, VT, LDVT, U, LDU, C, LDC, WORK, INFO)
Function/Subroutine Documentation
dbdsqr()
subroutine dbdsqr (character UPLO, integer N, integer NCVT, integer NRU, integer NCC, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(ldvt, *) VT, integer LDVT, double precision, dimension(ldu, *) U, integer LDU, double precision, dimension(ldc, *) C, integer LDC, double precision, dimension(*) WORK, integer INFO)
Definition at line 1 of file dbdsqr.f.
References dlartg(), dlas2(), dlasq1(), dlasr(), dlasv2(), drot(), dscal(), dswap(), and xerbla().