KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgebak.f File Reference
dgebak.f File Reference
Functions/Subroutines
subroutine dgebak (JOB, SIDE, N, ILO, IHI, SCALE, M, V, LDV, INFO)
Function/Subroutine Documentation
dgebak()
subroutine dgebak (character JOB, character SIDE, integer N, integer ILO, integer IHI, double precision, dimension(*) SCALE, integer M, double precision, dimension(ldv, *) V, integer LDV, integer INFO)
Definition at line 1 of file dgebak.f.
References dscal(), dswap(), and xerbla().