KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgebrd.f File Reference
dgebrd.f File Reference
Functions/Subroutines
subroutine dgebrd (M, N, A, LDA, D, E, TAUQ, TAUP, WORK, LWORK, INFO)
Function/Subroutine Documentation
dgebrd()
subroutine dgebrd (integer M, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(*) TAUQ, double precision, dimension(*) TAUP, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dgebrd.f.
References dgebd2(), dgemm(), dlabrd(), and xerbla().