KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgecon.f File Reference
dgecon.f File Reference
Functions/Subroutines
subroutine dgecon (NORM, N, A, LDA, ANORM, RCOND, WORK, IWORK, INFO)
Function/Subroutine Documentation
dgecon()
subroutine dgecon (character NORM, integer N, double precision, dimension(lda, *) A, integer LDA, double precision ANORM, double precision RCOND, double precision, dimension(*) WORK, integer, dimension(*) IWORK, integer INFO)
Definition at line 1 of file dgecon.f.
References dlacon(), dlatrs(), drscl(), and xerbla().