KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgeev.f File Reference
dgeev.f File Reference
Functions/Subroutines
subroutine dgeev (JOBVL, JOBVR, N, A, LDA, WR, WI, VL, LDVL, VR, LDVR, WORK, LWORK, INFO)
Function/Subroutine Documentation
dgeev()
subroutine dgeev (character JOBVL, character JOBVR, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) WR, double precision, dimension(*) WI, double precision, dimension(ldvl, *) VL, integer LDVL, double precision, dimension(ldvr, *) VR, integer LDVR, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dgeev.f.
References dgebak(), dgebal(), dgehrd(), dhseqr(), dlabad(), dlacpy(), dlartg(), dlascl(), dorghr(), drot(), dscal(), dtrevc(), and xerbla().