KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgelqf.f File Reference
dgelqf.f File Reference
Functions/Subroutines
subroutine dgelqf (M, N, A, LDA, TAU, WORK, LWORK, INFO)
Function/Subroutine Documentation
dgelqf()
subroutine dgelqf (integer M, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dgelqf.f.
References dgelq2(), dlarfb(), dlarft(), and xerbla().