KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgelss.f File Reference
dgelss.f File Reference
Functions/Subroutines
subroutine dgelss (M, N, NRHS, A, LDA, B, LDB, S, RCOND, RANK, WORK, LWORK, INFO)
Function/Subroutine Documentation
dgelss()
subroutine dgelss (integer M, integer N, integer NRHS, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision, dimension(*) S, double precision RCOND, integer RANK, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dgelss.f.
References dbdsqr(), dcopy(), dgebrd(), dgelqf(), dgemm(), dgemv(), dgeqrf(), dlabad(), dlacpy(), dlascl(), dlaset(), dorgbr(), dormbr(), dormlq(), dormqr(), drscl(), and xerbla().