KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgesvd.f File Reference
dgesvd.f File Reference
Functions/Subroutines
subroutine dgesvd (JOBU, JOBVT, M, N, A, LDA, S, U, LDU, VT, LDVT, WORK, LWORK, INFO)
Function/Subroutine Documentation
dgesvd()
subroutine dgesvd (character JOBU, character JOBVT, integer M, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) S, double precision, dimension(ldu, *) U, integer LDU, double precision, dimension(ldvt, *) VT, integer LDVT, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dgesvd.f.
References dbdsqr(), dgebrd(), dgelqf(), dgemm(), dgeqrf(), dlacpy(), dlascl(), dlaset(), dorgbr(), dorglq(), dorgqr(), dormbr(), and xerbla().