KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dgetf2.f File Reference
dgetf2.f File Reference
Functions/Subroutines
subroutine dgetf2 (M, N, A, LDA, IPIV, INFO)
Function/Subroutine Documentation
dgetf2()
subroutine dgetf2 (integer M, integer N, double precision, dimension(lda, *) A, integer LDA, integer, dimension(*) IPIV, integer INFO)
Definition at line 1 of file dgetf2.f.
References dger(), dscal(), dswap(), and xerbla().