KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dlahqr.f File Reference
dlahqr.f File Reference
Functions/Subroutines
subroutine dlahqr (WANTT, WANTZ, N, ILO, IHI, H, LDH, WR, WI, ILOZ, IHIZ, Z, LDZ, INFO)
Function/Subroutine Documentation
dlahqr()
subroutine dlahqr (logical WANTT, logical WANTZ, integer N, integer ILO, integer IHI, double precision, dimension(ldh, *) H, integer LDH, double precision, dimension(*) WR, double precision, dimension(*) WI, integer ILOZ, integer IHIZ, double precision, dimension(ldz, *) Z, integer LDZ, integer INFO)
Definition at line 1 of file dlahqr.f.
References dcopy(), dlabad(), dlanv2(), dlarfg(), and drot().