KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dlamch.f File Reference
dlamch.f File Reference
Functions/Subroutines
double precision function dlamch (CMACH)
subroutine dlamc1 (BETA, T, RND, IEEE1)
subroutine dlamc2 (BETA, T, RND, EPS, EMIN, RMIN, EMAX, RMAX)
double precision function dlamc3 (A, B)
subroutine dlamc4 (EMIN, START, BASE)
subroutine dlamc5 (BETA, P, EMIN, IEEE, EMAX, RMAX)
Function/Subroutine Documentation
dlamc1()
subroutine dlamc1 (integer BETA, integer T, logical RND, logical IEEE1)
Definition at line 131 of file dlamch.f.
dlamc2()
subroutine dlamc2 (integer BETA, integer T, logical RND, double precision EPS, integer EMIN, double precision RMIN, integer EMAX, double precision RMAX)
Definition at line 318 of file dlamch.f.
References dlamc1(), dlamc4(), and dlamc5().
dlamc3()
double precision function dlamc3 (double precision A, double precision B)
Definition at line 577 of file dlamch.f.
dlamc4()
subroutine dlamc4 (integer EMIN, double precision START, integer BASE)
Definition at line 615 of file dlamch.f.
dlamc5()
subroutine dlamc5 (integer BETA, integer P, integer EMIN, logical IEEE, integer EMAX, double precision RMAX)
Definition at line 699 of file dlamch.f.
dlamch()
double precision function dlamch (character CMACH)
Definition at line 1 of file dlamch.f.
References dlamc2(), and lsame().