KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dlatrd.f File Reference
dlatrd.f File Reference
Functions/Subroutines
subroutine dlatrd (UPLO, N, NB, A, LDA, E, TAU, W, LDW)
Function/Subroutine Documentation
dlatrd()
subroutine dlatrd (character UPLO, integer N, integer NB, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) E, double precision, dimension(*) TAU, double precision, dimension(ldw, *) W, integer LDW)
Definition at line 1 of file dlatrd.f.
References daxpy(), dgemv(), dlarfg(), dscal(), and dsymv().