KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dlatrs.f File Reference
dlatrs.f File Reference
Functions/Subroutines
subroutine dlatrs (UPLO, TRANS, DIAG, NORMIN, N, A, LDA, X, SCALE, CNORM, INFO)
Function/Subroutine Documentation
dlatrs()
subroutine dlatrs (character UPLO, character TRANS, character DIAG, character NORMIN, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, double precision SCALE, double precision, dimension(*) CNORM, integer INFO)
Definition at line 1 of file dlatrs.f.
References daxpy(), dscal(), dtrsv(), and xerbla().