KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dorg2r.f File Reference
dorg2r.f File Reference
Functions/Subroutines
subroutine dorg2r (M, N, K, A, LDA, TAU, WORK, INFO)
Function/Subroutine Documentation
dorg2r()
subroutine dorg2r (integer M, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer INFO)
Definition at line 1 of file dorg2r.f.
References dlarf(), dscal(), and xerbla().