KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dorgqr.f File Reference
dorgqr.f File Reference
Functions/Subroutines
subroutine dorgqr (M, N, K, A, LDA, TAU, WORK, LWORK, INFO)
Function/Subroutine Documentation
dorgqr()
subroutine dorgqr (integer M, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dorgqr.f.
References dlarfb(), dlarft(), dorg2r(), and xerbla().