KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dpotrf.f File Reference
dpotrf.f File Reference
Functions/Subroutines
subroutine dpotrf (UPLO, N, A, LDA, INFO)
Function/Subroutine Documentation
dpotrf()
subroutine dpotrf (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, integer INFO)
Definition at line 1 of file dpotrf.f.
References dgemm(), dpotf2(), dsyrk(), dtrsm(), and xerbla().