KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/dssum.f File Reference
dssum.f File Reference
Functions/Subroutines
subroutine setupds (gs_handle, nx, ny, nz, nel, melg, vertex, glo_num)
subroutine dssum (u, nx, ny, nz)
subroutine dsop (u, op, nx, ny, nz)
subroutine vec_dssum (u, v, w, nx, ny, nz)
subroutine vec_dsop (u, v, w, nx, ny, nz, op)
subroutine nvec_dssum (u, stride, n, gs_handle)
subroutine matvec3 (uout, Jmat, uin, iftrsp, n1, n2)
subroutine matvec3t (uout, Jmat, uin, iftrsp, n1, n2)
subroutine matvect (out, d, vec, n1, n2)
subroutine vectof_add (b, a, ie, iface, nx, ny, nz)
subroutine zero_f (b, ie, iface, nx, ny, nz)
subroutine ftovec_0 (a, b, ie, iface, nx, ny, nz)
subroutine ftovec (a, b, ie, iface, nx, ny, nz)
subroutine vectof (b, a, ie, iface, nx, ny, nz)
subroutine ftoveci (a, b, ie, iface, nx, ny, nz)
subroutine vectofi (b, a, ie, iface, nx, ny, nz)
subroutine apply_jt (u, nx, ny, nz, nel)
subroutine apply_j (u, nx, ny, nz, nel)
subroutine h1_proj (u, nx, ny, nz)
subroutine dssum_msk (u, mask, nx, ny, nz)
subroutine dssum_msk2 (u, mask, binv, nx, ny, nz)
subroutine gtpp_gs_op (u, op, hndl)
subroutine gtpp_gs_setup (hndl, nelgx, nelgy, nelgz, idir)
subroutine gs_setup_ms (hndl, nel, nx, ny, nz)
subroutine gs_op_ms (u, op, hndl)
Function/Subroutine Documentation
apply_j()
subroutine apply_j (real, dimension(1) u, nx, ny, nz, nel)
Definition at line 531 of file dssum.f.
References ftovec(), matvec3(), and vectof().
apply_jt()
subroutine apply_jt (real, dimension(1) u, nx, ny, nz, nel)
Definition at line 488 of file dssum.f.
References ftovec_0(), matvec3t(), matvect(), and vectof_add().
dsop()
subroutine dsop (real, dimension(1) u, character*3 op, nx, ny, nz)
Definition at line 100 of file dssum.f.
References nekgsync().
dssum()
subroutine dssum (real, dimension(1) u, nx, ny, nz)
Definition at line 33 of file dssum.f.
References dnekclock(), and nekgsync().
dssum_msk()
subroutine dssum_msk (real, dimension(1) u, real, dimension(1) mask, nx, ny, nz)
Definition at line 628 of file dssum.f.
References apply_j(), apply_jt(), col2(), dnekclock(), and nekgsync().
dssum_msk2()
subroutine dssum_msk2 (real, dimension(1) u, real, dimension(1) mask, real, dimension(1) binv, nx, ny, nz)
Definition at line 693 of file dssum.f.
References apply_j(), apply_jt(), col3(), dnekclock(), and nekgsync().
ftovec()
subroutine ftovec (real, dimension(nx,ny) a, real, dimension(nx,ny,nz,1) b, ie, iface, nx, ny, nz)
Definition at line 416 of file dssum.f.
References facind().
ftovec_0()
subroutine ftovec_0 (dimension(nx,ny) a, dimension(nx,ny,nz,1) b, ie, iface, nx, ny, nz)
Definition at line 397 of file dssum.f.
References facind().
ftoveci()
subroutine ftoveci (integer, dimension(nx,ny) a, integer, dimension(nx,ny,nz,1) b, ie, iface, nx, ny, nz)
Definition at line 452 of file dssum.f.
References facind().
gs_op_ms()
subroutine gs_op_ms (real, dimension(*) u, character*3 op, hndl)
Definition at line 891 of file dssum.f.
References exitti(), and nekgsync().
gs_setup_ms()
subroutine gs_setup_ms (integer hndl, nel, nx, ny, nz)
Definition at line 860 of file dssum.f.
gtpp_gs_op()
subroutine gtpp_gs_op (real, dimension(*) u, character*3 op, integer hndl)
Definition at line 760 of file dssum.f.
References exitti().
gtpp_gs_setup()
subroutine gtpp_gs_setup (integer hndl, integer nelgx, integer nelgy, integer nelgz, integer idir)
Definition at line 788 of file dssum.f.
References exitti(), and get_exyz().
h1_proj()
subroutine h1_proj (real, dimension(1) u, nx, ny, nz)
Definition at line 566 of file dssum.f.
References apply_j(), col2(), dnekclock(), and nekgsync().
matvec3()
subroutine matvec3 (real, dimension (1) uout, real, dimension (n1,n1,2) Jmat, real, dimension (1) uin, logical iftrsp, n1, n2)
Definition at line 290 of file dssum.f.
References copy(), mxm(), and transpose().
matvec3t()
subroutine matvec3t (real, dimension (n1,n2) uout, real, dimension (n1,n1,2) Jmat, real, dimension (n1,n2) uin, logical iftrsp, n1, n2)
Definition at line 316 of file dssum.f.
References copy(), mxm(), and transpose().
matvect()
subroutine matvect (dimension(1) out, dimension(n1,n2) d, dimension(1) vec, n1, n2)
Definition at line 339 of file dssum.f.
References mxm().
nvec_dssum()
subroutine nvec_dssum (real, dimension(1) u, integer stride, integer n, integer gs_handle)
Definition at line 260 of file dssum.f.
References dnekclock(), and nekgsync().
setupds()
subroutine setupds (integer gs_handle, nx, ny, nz, nel, melg, integer, dimension(1) vertex, integer*8, dimension(1) glo_num)
Definition at line 1 of file dssum.f.
References dnekclock(), and set_vert().
vec_dsop()
subroutine vec_dsop (real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, nx, ny, nz, character*3 op)
Definition at line 211 of file dssum.f.
References nekgsync().
vec_dssum()
subroutine vec_dssum (real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, nx, ny, nz)
Definition at line 163 of file dssum.f.
References dnekclock(), and nekgsync().
vectof()
subroutine vectof (real, dimension(nx,ny,nz,1) b, real, dimension(nx,ny) a, ie, iface, nx, ny, nz)
Definition at line 434 of file dssum.f.
References facind().
vectof_add()
subroutine vectof_add (dimension(nx,ny,nz,1) b, dimension(nx,ny) a, ie, iface, nx, ny, nz)
Definition at line 363 of file dssum.f.
References facind().
vectofi()
subroutine vectofi (integer, dimension(nx,ny,nz,1) b, integer, dimension(nx,ny) a, ie, iface, nx, ny, nz)
Definition at line 470 of file dssum.f.
References facind().
zero_f()
subroutine zero_f (dimension(nx,ny,nz,1) b, ie, iface, nx, ny, nz)
Definition at line 381 of file dssum.f.
References facind().