KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dstev.f File Reference
dstev.f File Reference
Functions/Subroutines
subroutine dstev (JOBZ, N, D, E, Z, LDZ, WORK, INFO)
Function/Subroutine Documentation
dstev()
subroutine dstev (character JOBZ, integer N, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(ldz, *) Z, integer LDZ, double precision, dimension(*) WORK, integer INFO)
Definition at line 1 of file dstev.f.
References dscal(), dsteqr(), dsterf(), and xerbla().