KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dsyev.f File Reference
dsyev.f File Reference
Functions/Subroutines
subroutine dsyev (JOBZ, UPLO, N, A, LDA, W, WORK, LWORK, INFO)
Function/Subroutine Documentation
dsyev()
subroutine dsyev (character JOBZ, character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) W, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dsyev.f.
References dlascl(), dorgtr(), dscal(), dsteqr(), dsterf(), dsytrd(), and xerbla().