KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dsygs2.f File Reference
dsygs2.f File Reference
Functions/Subroutines
subroutine dsygs2 (ITYPE, UPLO, N, A, LDA, B, LDB, INFO)
Function/Subroutine Documentation
dsygs2()
subroutine dsygs2 (integer ITYPE, character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, integer INFO)
Definition at line 1 of file dsygs2.f.
References daxpy(), dscal(), dsyr2(), dtrmv(), dtrsv(), and xerbla().