KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dsytrd.f File Reference
dsytrd.f File Reference
Functions/Subroutines
subroutine dsytrd (UPLO, N, A, LDA, D, E, TAU, WORK, LWORK, INFO)
Function/Subroutine Documentation
dsytrd()
subroutine dsytrd (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 1 of file dsytrd.f.
References dlatrd(), dsyr2k(), dsytd2(), and xerbla().