KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dsytd2.f File Reference
dsytd2.f File Reference
Functions/Subroutines
subroutine dsytd2 (UPLO, N, A, LDA, D, E, TAU, INFO)
Function/Subroutine Documentation
dsytd2()
subroutine dsytd2 (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(*) TAU, integer INFO)
Definition at line 1 of file dsytd2.f.
References daxpy(), dlarfg(), dsymv(), dsyr2(), and xerbla().