KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/dtrti2.f File Reference
dtrti2.f File Reference
Functions/Subroutines
subroutine dtrti2 (UPLO, DIAG, N, A, LDA, INFO)
DTRTI2 computes the inverse of a triangular matrix (unblocked algorithm).
Function/Subroutine Documentation
dtrti2()
subroutine dtrti2 (character UPLO, character DIAG, integer N, double precision, dimension(lda, *) A, integer LDA, integer INFO)
DTRTI2 computes the inverse of a triangular matrix (unblocked algorithm).
Download DTRTI2 + dependencies [TGZ] [ZIP] [TXT]
Purpose:
 DTRTI2 computes the inverse of a real upper or lower triangular
 matrix.
 This is the Level 2 BLAS version of the algorithm.
Parameters
[in] UPLO
          UPLO is CHARACTER*1
          Specifies whether the matrix A is upper or lower triangular.
          = 'U':  Upper triangular
          = 'L':  Lower triangular
[in] DIAG
          DIAG is CHARACTER*1
          Specifies whether or not the matrix A is unit triangular.
          = 'N':  Non-unit triangular
          = 'U':  Unit triangular
[in] N
          N is INTEGER
          The order of the matrix A.  N >= 0.
[in,out] A
          A is DOUBLE PRECISION array, dimension (LDA,N)
          On entry, the triangular matrix A.  If UPLO = 'U', the
          leading n by n upper triangular part of the array A contains
          the upper triangular matrix, and the strictly lower
          triangular part of A is not referenced.  If UPLO = 'L', the
          leading n by n lower triangular part of the array A contains
          the lower triangular matrix, and the strictly upper
          triangular part of A is not referenced.  If DIAG = 'U', the
          diagonal elements of A are also not referenced and are
          assumed to be 1.
          On exit, the (triangular) inverse of the original matrix, in
          the same storage format.
[in] LDA
          LDA is INTEGER
          The leading dimension of the array A.  LDA >= max(1,N).
[out] INFO
          INFO is INTEGER
          = 0: successful exit
          < 0: if INFO = -k, the k-th argument had an illegal value
Author
Univ. of Tennessee
Univ. of California Berkeley
Univ. of Colorado Denver
NAG Ltd.
Date
December 2016
Definition at line 111 of file dtrti2.f.
References dscal(), dtrmv(), and xerbla().