KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/fast3d.f File Reference
fast3d.f File Reference
Functions/Subroutines
subroutine gen_fast (df, sr, ss, st, x, y, z)
subroutine gen_fast_spacing (x, y, z)
subroutine plane_space_std (lr, ls, lt, i1, i2, w, x, y, z, nx, nxn, nz0, nzn)
subroutine plane_space (lr, ls, lt, i1, i2, w, x, y, z, nx, nxn, nz0, nzn)
subroutine plane_space2 (lr, ls, lt, i1, w, x, y, z, nx, nxn, nz0, nzn)
subroutine set_up_fast_1d_fem (s, lam, n, lbc, rbc, ll, lm, lr, z, nz, e)
subroutine set_up_1d_geom (dx, lbc, rbc, ll, lm, lr, z, nz)
subroutine gen_eigs_a_fem (sf, sft, atd, n, l, lbc, rbc)
subroutine get_fast_bc (lbr, rbr, lbs, rbs, lbt, rbt, e, bsym, ierr)
subroutine outv (x, n, name3)
subroutine outmat (a, m, n, name6, ie)
subroutine set_up_fast_1d_fem_ax (s, lam, n, lbc, rbc, ll, lm, lr, z, y, nz, ie)
subroutine set_up_1d_geom_ax (dx, lbc, rbc, ll, lm, lr, z, y, nz)
subroutine gen_eigs_a_fem_ax (sf, sft, atd, n, l, y, lbc, rbc)
subroutine load_semhat_weighted
subroutine do_semhat_weight (jgl, dgl, bgl, n)
subroutine semhat (a, b, c, d, z, dgll, jgll, bgl, zgl, dgl, jgl, n, w)
subroutine fd_weights_full (xx, x, n, m, c)
subroutine set_up_fast_1d_sem (s, lam, n, lbc, rbc, ll, lm, lr, ie)
subroutine set_up_fast_1d_sem_op (g, b0, b1, l, r, ll, lm, lr, bh, jgl, jscl)
subroutine swap_lengths
subroutine row_zero (a, m, n, e)
subroutine mhd_bc_dn (ibc, face, e)
Function/Subroutine Documentation
do_semhat_weight()
subroutine do_semhat_weight (real, dimension(1:n-1,0:n) jgl, real, dimension(1:n-1,0:n) dgl, real, dimension(1:n-1) bgl, n)
Definition at line 1199 of file fast3d.f.
fd_weights_full()
subroutine fd_weights_full (xx, real, dimension(0:n) x, n, m, real, dimension(0:n,0:m) c)
Definition at line 1292 of file fast3d.f.
gen_eigs_a_fem()
subroutine gen_eigs_a_fem (real, dimension(n,n) sf, real, dimension(n,n) sft, real, dimension(1) atd, n, real, dimension(0:1) l, integer lbc, integer rbc)
Definition at line 657 of file fast3d.f.
References calcz(), chsign(), cmult(), exitt(), mynode(), rzero(), sort(), swap(), transpose(), vlmax(), vlsc3(), and vlsum().
gen_eigs_a_fem_ax()
subroutine gen_eigs_a_fem_ax (real, dimension(n,n) sf, real, dimension(n,n) sft, real, dimension(1) atd, n, real, dimension(0:1) l, real, dimension(1) y, integer lbc, integer rbc)
Definition at line 1036 of file fast3d.f.
References calcz(), chsign(), cmult(), exitt(), mynode(), rzero(), sort(), swap(), transpose(), vlmax(), vlsc3(), and vlsum().
gen_fast()
subroutine gen_fast (real, dimension(lx1*ly1*lz1,1) df, real, dimension(lxx*2,1) sr, real, dimension(lxx*2,1) ss, real, dimension(lxx*2,1) st, real, dimension(lx1,ly1,lz1,nelv) x, real, dimension(lx1,ly1,lz1,nelv) y, real, dimension(lx1,ly1,lz1,nelv) z)
Definition at line 2 of file fast3d.f.
References exitti(), get_fast_bc(), iglmax(), set_up_fast_1d_fem(), set_up_fast_1d_fem_ax(), set_up_fast_1d_sem(), vlmax(), vlsc2(), and vlsum().
gen_fast_spacing()
subroutine gen_fast_spacing (real, dimension(lx1,ly1,lz1,nelv) x, real, dimension(lx1,ly1,lz1,nelv) y, real, dimension(lx1,ly1,lz1,nelv) z)
Definition at line 142 of file fast3d.f.
References load_semhat_weighted(), plane_space(), and plane_space2().
get_fast_bc()
subroutine get_fast_bc (integer lbr, integer rbr, integer lbs, integer rbs, integer lbt, integer rbt, integer e, integer bsym, ierr)
Definition at line 802 of file fast3d.f.
References exitti(), and mhd_bc_dn().
load_semhat_weighted()
subroutine load_semhat_weighted
Definition at line 1181 of file fast3d.f.
References do_semhat_weight(), and semhat().
mhd_bc_dn()
subroutine mhd_bc_dn (ibc, integer face, integer e)
Definition at line 1625 of file fast3d.f.
References indx1().
outmat()
subroutine outmat (real, dimension(m,n) a, m, n, character*6 name6, ie)
Definition at line 890 of file fast3d.f.
outv()
subroutine outv (real, dimension(1) x, n, character*3 name3)
Definition at line 879 of file fast3d.f.
plane_space()
subroutine plane_space (real, dimension(1) lr, real, dimension(1) ls, real, dimension(1) lt, i1, i2, real, dimension(1) w, real, dimension(0:nxn,0:nxn,nz0:nzn,1) x, real, dimension(0:nxn,0:nxn,nz0:nzn,1) y, real, dimension(0:nxn,0:nxn,nz0:nzn,1) z, nx, nxn, nz0, nzn)
Definition at line 306 of file fast3d.f.
plane_space2()
subroutine plane_space2 (real, dimension(1) lr, real, dimension(1) ls, real, dimension(1) lt, i1, real, dimension(1) w, real, dimension(0:nxn,0:nxn,nz0:nzn,1) x, real, dimension(0:nxn,0:nxn,nz0:nzn,1) y, real, dimension(0:nxn,0:nxn,nz0:nzn,1) z, nx, nxn, nz0, nzn)
Definition at line 425 of file fast3d.f.
plane_space_std()
subroutine plane_space_std (real, dimension(1) lr, real, dimension(1) ls, real, dimension(1) lt, i1, i2, real, dimension(1) w, real, dimension(0:nxn,0:nxn,nz0:nzn,1) x, real, dimension(0:nxn,0:nxn,nz0:nzn,1) y, real, dimension(0:nxn,0:nxn,nz0:nzn,1) z, nx, nxn, nz0, nzn)
Definition at line 203 of file fast3d.f.
row_zero()
subroutine row_zero (real, dimension(m,n) a, integer m, integer n, integer e)
Definition at line 1616 of file fast3d.f.
semhat()
subroutine semhat (real, dimension(0:n,0:n) a, real, dimension(0:n) b, real, dimension(0:n,0:n) c, real, dimension(0:n,0:n) d, real, dimension(0:n) z, real, dimension(0:n,1:n-1) dgll, real, dimension(0:n,1:n-1) jgll, real, dimension(1:n-1) bgl, real, dimension(1:n-1) zgl, real, dimension(1:n-1,0:n) dgl, real, dimension(1:n-1,0:n) jgl, n, real, dimension(0:2*n+1) w)
Definition at line 1215 of file fast3d.f.
References fd_weights_full(), rzero(), zwgl(), and zwgll().
set_up_1d_geom()
subroutine set_up_1d_geom (real, dimension(0:1) dx, integer lbc, integer rbc, real ll, real lm, real lr, real, dimension(2) z, nz)
Definition at line 561 of file fast3d.f.
References rone(), and scale().
set_up_1d_geom_ax()
subroutine set_up_1d_geom_ax (real, dimension(0:1) dx, integer lbc, integer rbc, real ll, real lm, real lr, real, dimension(2) z, real, dimension(1) y, nz)
Definition at line 940 of file fast3d.f.
References rone(), and scale().
set_up_fast_1d_fem()
subroutine set_up_fast_1d_fem (real, dimension(1) s, real, dimension(1) lam, n, integer lbc, integer rbc, real ll, real lm, real lr, real, dimension(1) z, nz, integer e)
Definition at line 527 of file fast3d.f.
References exitt(), gen_eigs_a_fem(), and set_up_1d_geom().
set_up_fast_1d_fem_ax()
subroutine set_up_fast_1d_fem_ax (real, dimension(1) s, real, dimension(1) lam, n, integer lbc, integer rbc, real ll, real lm, real lr, real, dimension(1) z, real, dimension(1) y, nz, ie)
Definition at line 905 of file fast3d.f.
References exitt(), gen_eigs_a_fem_ax(), and set_up_1d_geom_ax().
set_up_fast_1d_sem()
subroutine set_up_fast_1d_sem (real, dimension(1) s, real, dimension(1) lam, integer n, integer lbc, integer rbc, real ll, real lm, real lr, ie)
Definition at line 1349 of file fast3d.f.
References generalev(), row_zero(), set_up_fast_1d_sem_op(), and transpose().
set_up_fast_1d_sem_op()
subroutine set_up_fast_1d_sem_op (real, dimension(0:lx1-1,0:lx1-1) g, integer b0, integer b1, logical l, logical r, real ll, real lm, real lr, real, dimension(0:lx1-1) bh, real, dimension(1:lx2,0:lx1-1) jgl, integer jscl)
Definition at line 1408 of file fast3d.f.
References rzero().
swap_lengths()
subroutine swap_lengths
Definition at line 1540 of file fast3d.f.
References dssum(), and plane_space().