KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/3rd_party/finiparser.c File Reference
finiparser.c File Reference
#include <ctype.h>
#include "iniparser.h"
Macros
#define FNAME_H
#define FORTRAN_NAME(low, up) low
#define finiparser_dump FORTRAN_NAME(finiparser_dump, FINIPARSER_DUMP)
#define finiparser_getPair FORTRAN_NAME(finiparser_getpair, FINIPARSER_GETPAIR)
#define finiparser_load FORTRAN_NAME(finiparser_load, FINIPARSER_LOAD)
#define finiparser_free FORTRAN_NAME(finiparser_free, FINIPARSER_FREE)
#define finiparser_getString FORTRAN_NAME(finiparser_getstring, FINIPARSER_GETSTRING)
#define finiparser_getDictEntries FORTRAN_NAME(finiparser_getdictentries, FINIPARSER_GETDICTENTRIES)
#define finiparser_getBool FORTRAN_NAME(finiparser_getbool, FINIPARSER_GETBOOL)
#define finiparser_find FORTRAN_NAME(finiparser_find, FINIPARSER_FIND)
#define finiparser_getDbl FORTRAN_NAME(finiparser_getdbl, FINIPARSER_GETDBL)
#define finiparser_getToken FORTRAN_NAME(finiparser_gettoken, FINIPARSER_GETTOKEN)
#define finiparser_findTokens FORTRAN_NAME(finiparser_findtokens, FINIPARSER_FINDTOKENS)
#define ntokenmax 100
Functions
char * addchar0 (char *str, int str_len)
void finiparser_find (int *out, char *key, int *ifnd, int key_len)
void finiparser_getDictEntries (int *n)
void finiparser_getPair (char *key, char *val, int *id, int *ifnd, int key_len, int val_len)
void finiparser_load (char *fname, int *ierr, int fname_len)
void finiparser_getString (char *out, char *key, int *ifnd, int out_len, int key_len)
void finiparser_getBool (int *out, char *key, int *ifnd, int key_len)
void finiparser_getDbl (double *out, char *key, int *ifnd, int key_len)
void finiparser_getToken (char *out, int *id, int out_len)
void finiparser_findTokens (char *key, char *delim, int *icounter, int key_len, int delim_len)
Macro Definition Documentation
finiparser_dump
void finiparser_dump FORTRAN_NAME(finiparser_dump, FINIPARSER_DUMP)
Definition at line 26 of file finiparser.c.
finiparser_find
#define finiparser_find FORTRAN_NAME(finiparser_find, FINIPARSER_FIND)
Definition at line 33 of file finiparser.c.
finiparser_findTokens
#define finiparser_findTokens FORTRAN_NAME(finiparser_findtokens, FINIPARSER_FINDTOKENS)
Definition at line 36 of file finiparser.c.
finiparser_free
void finiparser_free FORTRAN_NAME(finiparser_free, FINIPARSER_FREE)
Definition at line 29 of file finiparser.c.
finiparser_getBool
#define finiparser_getBool FORTRAN_NAME(finiparser_getbool, FINIPARSER_GETBOOL)
Definition at line 32 of file finiparser.c.
finiparser_getDbl
#define finiparser_getDbl FORTRAN_NAME(finiparser_getdbl, FINIPARSER_GETDBL)
Definition at line 34 of file finiparser.c.
finiparser_getDictEntries
#define finiparser_getDictEntries FORTRAN_NAME(finiparser_getdictentries, FINIPARSER_GETDICTENTRIES)
Definition at line 31 of file finiparser.c.
finiparser_getPair
#define finiparser_getPair FORTRAN_NAME(finiparser_getpair, FINIPARSER_GETPAIR)
Definition at line 27 of file finiparser.c.
finiparser_getString
#define finiparser_getString FORTRAN_NAME(finiparser_getstring, FINIPARSER_GETSTRING)
Definition at line 30 of file finiparser.c.
finiparser_getToken
#define finiparser_getToken FORTRAN_NAME(finiparser_gettoken, FINIPARSER_GETTOKEN)
Definition at line 35 of file finiparser.c.
finiparser_load
#define finiparser_load FORTRAN_NAME(finiparser_load, FINIPARSER_LOAD)
Definition at line 28 of file finiparser.c.
FNAME_H
#define FNAME_H
Definition at line 5 of file finiparser.c.
FORTRAN_NAME
#define FORTRAN_NAME (low, up) low
Definition at line 20 of file finiparser.c.
ntokenmax
#define ntokenmax 100
Definition at line 38 of file finiparser.c.
Function Documentation
addchar0()
char* addchar0 (char * str, int str_len)
Definition at line 44 of file finiparser.c.
finiparser_find()
void finiparser_find (int * out, char * key, int * ifnd, int key_len)
Definition at line 71 of file finiparser.c.
References addchar0(), and iniparser_find_entry().
finiparser_findTokens()
void finiparser_findTokens (char * key, char * delim, int * icounter, int key_len, int delim_len)
Definition at line 202 of file finiparser.c.
References addchar0(), and iniparser_getstring().
finiparser_getBool()
void finiparser_getBool (int * out, char * key, int * ifnd, int key_len)
Definition at line 159 of file finiparser.c.
References addchar0(), and iniparser_getboolean().
finiparser_getDbl()
void finiparser_getDbl (double * out, char * key, int * ifnd, int key_len)
Definition at line 175 of file finiparser.c.
References addchar0(), and iniparser_getstring().
finiparser_getDictEntries()
void finiparser_getDictEntries (int * n)
Definition at line 87 of file finiparser.c.
finiparser_getPair()
void finiparser_getPair (char * key, char * val, int * id, int * ifnd, int key_len, int val_len)
Definition at line 94 of file finiparser.c.
finiparser_getString()
void finiparser_getString (char * out, char * key, int * ifnd, int out_len, int key_len)
Definition at line 136 of file finiparser.c.
References addchar0(), and iniparser_getstring().
finiparser_getToken()
void finiparser_getToken (char * out, int * id, int out_len)
Definition at line 191 of file finiparser.c.
References ntokenmax.
finiparser_load()
void finiparser_load (char * fname, int * ierr, int fname_len)
Definition at line 118 of file finiparser.c.
References addchar0().