KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/genxyz.f File Reference
genxyz.f File Reference
Functions/Subroutines
subroutine arcsrf (xml, yml, zml, nxl, nyl, nzl, ie, isid)
subroutine defsrf (xml, yml, zml, nxl, nyl, nzl, ie, iface1, ccv)
subroutine intrsc (x3, x2, x1, delt, ie, iface)
subroutine zbrac (x1, x2, succes)
function zbrent (X1, X2, TOL)
function fnc (ETA)
subroutine setdef
logical function ifvchk (VEC, I1, I2, I3)
subroutine gencoor (xm3, ym3, zm3)
subroutine genxyz (xml, yml, zml, nxl, nyl, nzl)
subroutine sethmat (h, zgml, nxl, nyl, nzl)
subroutine setzgml (zgml, e, nxl, nyl, nzl, ifaxl)
subroutine sphsrf (xml, yml, zml, ifce, ie, nx, ny, nz, xysrf)
subroutine edg3d (xysrf, x1, x2, i1, i2, j1, j2, nx, ny)
real function dot (V1, V2, N)
subroutine cross (v1, v2, v3)
subroutine norm3d (v1)
subroutine crn3d (xcv, xc, yc, zc, curve, iface)
subroutine rotxyz
subroutine gensrf (XML, YML, ZML, IFCE, IE, MX, MY, MZ, zgml)
subroutine prjects (x0, dxc, c, cc)
subroutine srfind (x1, x0, c, cc)
function ressrf (x, c, cc)
subroutine linquad (xl, yl, zl, nxl, nyl, nzl)
subroutine xyzlin (xl, yl, zl, nxl, nyl, nzl, e, ifaxl)
subroutine xyzquad (xl, yl, zl, nxl, nyl, nzl, e)
subroutine clean_xyzq (x, y, z, if3d)
subroutine mesh_metrics
real function dist_xyzc (i, j, ie)
function dxmin_e (e)
function dxmax_e (e)
Function/Subroutine Documentation
arcsrf()
subroutine arcsrf (dimension(nxl,nyl,nzl,1) xml, dimension(nxl,nyl,nzl,1) yml, dimension(nxl,nyl,nzl,1) zml, nxl, nyl, nzl, ie, isid)
Definition at line 2 of file genxyz.f.
References addtnsr(), exitt(), and mod1().
clean_xyzq()
subroutine clean_xyzq (real, dimension(3,3,3) x, real, dimension(3,3,3) y, real, dimension(3,3,3) z, logical if3d)
Definition at line 1412 of file genxyz.f.
crn3d()
subroutine crn3d (dimension(3,2,2) xcv, dimension(8) xc, dimension(8) yc, dimension(8) zc, dimension(4) curve, iface)
Definition at line 928 of file genxyz.f.
References exitt().
cross()
subroutine cross (dimension(3) v1, dimension(3) v2, dimension(3) v3)
Definition at line 898 of file genxyz.f.
defsrf()
subroutine defsrf (dimension(nxl,nyl,nzl,1) xml, dimension(nxl,nyl,nzl,1) yml, dimension(nxl,nyl,nzl,1) zml, nxl, nyl, nzl, ie, iface1, character*1 ccv)
Definition at line 103 of file genxyz.f.
References dsset(), and intrsc().
dist_xyzc()
real function dist_xyzc (i, j, ie)
Definition at line 1519 of file genxyz.f.
dot()
real function dot (dimension(n) V1, dimension(n) V2, N)
Definition at line 884 of file genxyz.f.
dxmax_e()
function dxmax_e (integer e)
Definition at line 1589 of file genxyz.f.
dxmin_e()
function dxmin_e (integer e)
Definition at line 1534 of file genxyz.f.
edg3d()
subroutine edg3d (dimension(3,nx,ny) xysrf, dimension(3) x1, dimension(3) x2, i1, i2, j1, j2, nx, ny)
Definition at line 843 of file genxyz.f.
References copy(), cross(), dot(), and norm3d().
fnc()
function fnc (ETA)
Definition at line 324 of file genxyz.f.
gencoor()
subroutine gencoor (dimension(lx3,ly3,lz3,1) xm3, dimension(lx3,ly3,lz3,1) ym3, dimension(lx3,ly3,lz3,1) zm3)
Definition at line 533 of file genxyz.f.
References genxyz().
gensrf()
subroutine gensrf (dimension(mx,my,mz,1) XML, dimension(mx,my,mz,1) YML, dimension(mx,my,mz,1) ZML, IFCE, IE, MX, MY, MZ, dimension(mx,3) zgml)
Definition at line 1022 of file genxyz.f.
References dsset(), and prjects().
genxyz()
subroutine genxyz (real, dimension(nxl,nyl,nzl,1) xml, real, dimension(nxl,nyl,nzl,1) yml, real, dimension(nxl,nyl,nzl,1) zml, nxl, nyl, nzl)
Definition at line 557 of file genxyz.f.
References arcsrf(), gensrf(), linquad(), sethmat(), setzgml(), and sphsrf().
ifvchk()
logical function ifvchk (dimension(3,12) VEC, I1, I2, I3)
Definition at line 509 of file genxyz.f.
References dot().
intrsc()
subroutine intrsc (dimension(3) x3, dimension(3) x2, dimension(3) x1, delt, ie, iface)
Definition at line 167 of file genxyz.f.
References zbrac(), and zbrent().
linquad()
subroutine linquad (real, dimension(nxl*nyl*nzl,1) xl, real, dimension(nxl*nyl*nzl,1) yl, real, dimension(nxl*nyl*nzl,1) zl, nxl, nyl, nzl)
Definition at line 1234 of file genxyz.f.
References xyzlin(), and xyzquad().
mesh_metrics()
subroutine mesh_metrics
Definition at line 1436 of file genxyz.f.
References dist_xyzc(), dxmax_e(), dxmin_e(), glmax(), glmin(), glsum(), vlmax(), vlmin(), and vlsum().
norm3d()
subroutine norm3d (dimension(3) v1)
Definition at line 911 of file genxyz.f.
References dot().
prjects()
subroutine prjects (real, dimension(3) x0, dxc, real, dimension(5) c, character*1 cc)
Definition at line 1117 of file genxyz.f.
References copy(), ressrf(), and srfind().
ressrf()
function ressrf (real, dimension(3) x, real, dimension(5) c, character*1 cc)
Definition at line 1218 of file genxyz.f.
rotxyz()
subroutine rotxyz
Definition at line 976 of file genxyz.f.
References vlsum().
setdef()
subroutine setdef
Definition at line 351 of file genxyz.f.
References rzero().
sethmat()
subroutine sethmat (real, dimension(lx1,3,2) h, real, dimension(lx1,3) zgml, nxl, nyl, nzl)
Definition at line 612 of file genxyz.f.
References rone().
setzgml()
subroutine setzgml (real, dimension(lx1,3) zgml, integer e, nxl, nyl, nzl, logical ifaxl)
Definition at line 640 of file genxyz.f.
References copy(), exitti(), and rzero().
sphsrf()
subroutine sphsrf (dimension(nx,ny,nz,1) xml, dimension(nx,ny,nz,1) yml, dimension(nx,ny,nz,1) zml, ifce, ie, nx, ny, nz, dimension(3,nx,nz) xysrf)
Definition at line 676 of file genxyz.f.
References cmult(), crn3d(), cross(), dot(), dsset(), edg3d(), and norm3d().
srfind()
subroutine srfind (real, dimension(3) x1, real, dimension(3) x0, real, dimension(5) c, character*1 cc)
Definition at line 1182 of file genxyz.f.
References ressrf().
xyzlin()
subroutine xyzlin (real, dimension(nxl,nyl,nzl) xl, real, dimension(nxl,nyl,nzl) yl, real, dimension(nxl,nyl,nzl) zl, nxl, nyl, nzl, integer e, logical ifaxl)
Definition at line 1268 of file genxyz.f.
References fd_weights_full(), setzgml(), tensr3(), and transpose().
xyzquad()
subroutine xyzquad (real, dimension(nxl,nyl,nzl) xl, real, dimension(nxl,nyl,nzl) yl, real, dimension(nxl,nyl,nzl) zl, nxl, nyl, nzl, integer e)
Definition at line 1333 of file genxyz.f.
References clean_xyzq(), fd_weights_full(), gh_face_extend(), gh_face_extend_2d(), setzgml(), tensr3(), transpose(), and xyzlin().
zbrac()
subroutine zbrac (x1, x2, logical succes)
Definition at line 206 of file genxyz.f.
References fnc().
zbrent()
function zbrent (X1, X2, TOL)
Definition at line 237 of file genxyz.f.
References fnc().