KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/gfldr.f File Reference
gfldr.f File Reference
Functions/Subroutines
subroutine gfldr (sourcefld)
subroutine gfldr_getxyz (xout, yout, zout)
subroutine gfldr_getfld (out1, out2, out3, nout, nldim, ifldpos)
subroutine gfldr_buf2vi (vi, index, buf, ldim, wds, nel, nxyz)
subroutine gfldr_intp (fieldout, nout, fieldin, iffpts)
Function/Subroutine Documentation
gfldr()
subroutine gfldr (character, dimension(*) sourcefld)
Definition at line 3 of file gfldr.f.
References axis_interp_ic(), byte_close_mpi(), byte_open_mpi(), byte_read_mpi(), dnekclock_sync(), err_chk(), exitt(), exitti(), gfldr_getfld(), gfldr_getxyz(), igl_running_sum(), map_pm1_to_pr(), and mfi_parse_hdr().
gfldr_buf2vi()
subroutine gfldr_buf2vi (real, dimension(*) vi, index, real*4, dimension(*) buf, ldim, integer wds, nel, nxyz)
Definition at line 239 of file gfldr.f.
References copy(), and copy4r().
gfldr_getfld()
subroutine gfldr_getfld (real, dimension(*) out1, real, dimension(*) out2, real, dimension(*) out3, nout, nldim, ifldpos)
Definition at line 185 of file gfldr.f.
References byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), gfldr_buf2vi(), and gfldr_intp().
gfldr_getxyz()
subroutine gfldr_getxyz (real, dimension(*) xout, real, dimension(*) yout, real, dimension(*) zout)
Definition at line 154 of file gfldr.f.
References byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), and gfldr_buf2vi().
gfldr_intp()
subroutine gfldr_intp (real, dimension(nout) fieldout, nout, real, dimension (*) fieldin, logical iffpts)
Definition at line 260 of file gfldr.f.