KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/gmres.f File Reference
gmres.f File Reference
Functions/Subroutines
subroutine uzawa_gmres (res, h1, h2, h2inv, intype, iter)
subroutine uzawa_gmres_split0 (l, u, b, binv, n)
subroutine uzawa_gmres_split (l, u, b, binv, n)
subroutine uzawa_gmres_temp (a, b, n)
subroutine ax (w, x, h1, h2, n)
subroutine hmh_gmres (res, h1, h2, wt, iter)
subroutine set_overlap2
subroutine h1_overlap_2 (u, v, mask)
subroutine dd_swap_vals (v1, v0, gsh_dd)
subroutine gen_fast_g
subroutine set_up_fast_1d_sem_g (s, lam, n, lbc, rbc, ll, lm, lr, ie)
subroutine set_up_fast_1d_sem_op_a (g, b0, b1, l, r, ll, lm, lr, ah)
subroutine set_up_fast_1d_sem_op_b (g, b0, b1, l, r, ll, lm, lr, bh)
subroutine fill_interior_g (v1, v, e, nx, nz, iz1, nel)
subroutine dface_ext_g (x, t, e, nx, nz)
subroutine dface_add1si_g (x, c, t, e, nx, nz)
subroutine fastdm1_g (R, ie, w1, w2)
subroutine s_face_to_int2_g (x, c, t, e, nx, nz)
subroutine outfldr_g (x, txt10, nx, nz, ichk)
subroutine outfldi_g (x, txt10, nx, nz, ichk)
subroutine setupds_no_crn (gs_h, nx, ny, nz, nel, melg, vertex, glo_num)
subroutine rzero_g (a, e, nx, ny, nz)
Function/Subroutine Documentation
ax()
subroutine ax (real, dimension(n) w, real, dimension(n) x, real, dimension(n) h1, real, dimension(n) h2, integer n)
Definition at line 284 of file gmres.f.
References axhelm(), col2(), and dssum().
dd_swap_vals()
subroutine dd_swap_vals (real, dimension(lxs,lys,lzs,lelt) v1, real, dimension(lx1,ly1,lz1,lelt) v0, integer gsh_dd)
Definition at line 609 of file gmres.f.
References dface_add1si_g(), dface_ext_g(), fastdm1_g(), fill_interior_g(), rzero_g(), and s_face_to_int2_g().
dface_add1si_g()
subroutine dface_add1si_g (real, dimension(nx,nx,nz,1) x, c, integer t, integer e, nx, nz)
Definition at line 1028 of file gmres.f.
dface_ext_g()
subroutine dface_ext_g (real, dimension(nx,nx,nz,1) x, integer t, integer e, nx, nz)
Definition at line 983 of file gmres.f.
fastdm1_g()
subroutine fastdm1_g (real, dimension(1) R, ie, real, dimension(1) w1, real, dimension(1) w2)
Definition at line 1078 of file gmres.f.
References col2(), and tensr3().
fill_interior_g()
subroutine fill_interior_g (real, dimension(nx+2,nx+2,nz+2*iz1,nel) v1, real, dimension (nx ,nx ,nz ,nel) v, integer e, nx, nz, iz1, nel)
Definition at line 964 of file gmres.f.
gen_fast_g()
subroutine gen_fast_g
Definition at line 659 of file gmres.f.
References get_fast_bc(), load_semhat_weighted(), set_up_fast_1d_sem_g(), and vlmax().
h1_overlap_2()
subroutine h1_overlap_2 (real, dimension(lx1,lx1,lz1,1) u, real, dimension(1) v, real, dimension(1) mask)
Definition at line 571 of file gmres.f.
References col2(), dd_swap_vals(), and dssum().
hmh_gmres()
subroutine hmh_gmres (real, dimension (lx1*ly1*lz1*lelv) res, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension (lx1,ly1,lz1,lelv) wt, iter)
Definition at line 304 of file gmres.f.
References add2(), add2s2(), ax(), chktcg1(), cmult2(), col2(), col3(), copy(), crs_solve_h1(), dnekclock(), fdm_h1(), fem_amg_solve, glsc3(), gop(), h1_overlap_2(), h1mg_solve(), ortho(), rzero(), set_fdm_prec_h1b(), uzawa_gmres_split(), and vlsc3().
outfldi_g()
subroutine outfldi_g (integer, dimension(nx,nx,nz,lelt) x, character*10 txt10, nx, nz, ichk)
Definition at line 1226 of file gmres.f.
References checkit(), iglmax(), and iglmin().
outfldr_g()
subroutine outfldr_g (real, dimension(nx,nx,nz,lelt) x, character*10 txt10, nx, nz, ichk)
Definition at line 1163 of file gmres.f.
References checkit(), glmax(), and glmin().
rzero_g()
subroutine rzero_g (real, dimension(nx,ny,nz,1) a, integer e, nx, ny, nz)
Definition at line 1334 of file gmres.f.
s_face_to_int2_g()
subroutine s_face_to_int2_g (real, dimension(nx,nx,nz,1) x, c, integer t, integer e, nx, nz)
Definition at line 1113 of file gmres.f.
set_overlap2()
subroutine set_overlap2
Definition at line 547 of file gmres.f.
References gen_fast_g(), setupds_no_crn(), and swap_lengths().
set_up_fast_1d_sem_g()
subroutine set_up_fast_1d_sem_g (real, dimension(1) s, real, dimension(1) lam, integer n, integer lbc, integer rbc, real ll, real lm, real lr, ie)
Definition at line 754 of file gmres.f.
References generalev(), row_zero(), set_up_fast_1d_sem_op_a(), set_up_fast_1d_sem_op_b(), and transpose().
set_up_fast_1d_sem_op_a()
subroutine set_up_fast_1d_sem_op_a (real, dimension(0:lx1+1,0:lx1+1) g, integer b0, integer b1, logical l, logical r, real ll, real lm, real lr, real, dimension(0:lx1-1,0:lx1-1) ah)
Definition at line 807 of file gmres.f.
References rzero().
set_up_fast_1d_sem_op_b()
subroutine set_up_fast_1d_sem_op_b (real, dimension(0:lx1+1,0:lx1+1) g, integer b0, integer b1, logical l, logical r, real ll, real lm, real lr, real, dimension(0:lx1-1) bh)
Definition at line 889 of file gmres.f.
References rzero().
setupds_no_crn()
subroutine setupds_no_crn (integer gs_h, nx, ny, nz, nel, melg, integer, dimension(1) vertex, integer*8, dimension(nx,ny,nz,nel) glo_num)
Definition at line 1289 of file gmres.f.
References dnekclock(), and set_vert().
uzawa_gmres()
subroutine uzawa_gmres (real, dimension (lx2*ly2*lz2*lelv) res, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, intype, iter)
Definition at line 2 of file gmres.f.
References add2s2(), cdabdtp(), chktcg2(), cmult2(), col2(), col3(), copy(), dnekclock(), glsc2(), gop(), hsmg_solve(), ortho(), rzero(), uzawa_gmres_split0(), uzprec(), and vlsc2().
uzawa_gmres_split()
subroutine uzawa_gmres_split (real, dimension(n) l, real, dimension(n) u, real, dimension(n) b, real, dimension(n) binv, integer n)
Definition at line 252 of file gmres.f.
uzawa_gmres_split0()
subroutine uzawa_gmres_split0 (real, dimension(n) l, real, dimension(n) u, real, dimension(n) b, real, dimension(n) binv, integer n)
Definition at line 239 of file gmres.f.
uzawa_gmres_temp()
subroutine uzawa_gmres_temp (real, dimension(n) a, real, dimension(n) b, integer n)
Definition at line 274 of file gmres.f.