KTH framework for Nek5000 toolboxes; testing version: Math
Math
Framework for Nek5000 toolboxes » Toolbox » Utility module
Diverse tools for matht or data operations.
Files
file math_tools.f
Set of math related tools for KTH modules.
Functions
real function math_stepf (x)
Step function.
real function math_ran_dst (ix, iy, iz, ieg, xl, fcoeff)
Give random distribution depending on position.
real function math_ran_rng (lower, upper)
Give random number in the defined range.
real function math_zbqlu01 ()
Marsaglia-Zaman random number generator.
subroutine math_zbqlini (seed)
Initialise Marsaglia-Zaman random number generator.
subroutine math_edgind (istart, istop, iskip, iedg, nx, ny, nz)
Give bounds for loops to extract edge of a 3D element.
subroutine math_etovec (vec, edg, vfld, nx, ny, nz)
Extract 3D element edge.
subroutine math_rot3da (vo, vi, va, an)
3D rotation of a vector along given axis.
Detailed Description
Diverse tools for matht or data operations.
Set of math related routines for toolbox
Module interface:
Global interface list:
Interface provided:
math_stepf
math_ran_dst
math_ran_rng
math_zbqlu01
math_zbqlini
math_edgind
math_etovec
math_rot3da
Function Documentation
math_edgind()
subroutine math_edgind (integer istart, integer istop, integer iskip, integer iedg, integer nx, integer ny, integer nz)
Give bounds for loops to extract edge of a 3D element.
Note
All edge related routines used IXCN and ESKIP, but this caused some problems as these arrays have to be continuosly updated for different levels in pressure solver, so I add this routine.
Parameters
[out] istart lower loop bound
[out] istop upper loop bound
[out] iskip stride
[in] iedg edge number
[in] nx,ny,nz element size
Definition at line 252 of file math_tools.f.
math_etovec()
subroutine math_etovec (real, dimension(nx) vec, integer edg, real, dimension(nx*ny*nz) vfld, integer nx, integer ny, integer nz)
Extract 3D element edge.
Note
This routine works on singe element not the whole field.
Parameters
[out] vec vector containg edge values
[in] edg edge number
[in] vfld pointer to singe element in the field
[in] nx,ny,nz element size
Definition at line 298 of file math_tools.f.
References math_edgind().
math_ran_dst()
real function math_ran_dst (integer ix, integer iy, integer iz, integer ieg, real, dimension(ldim) xl, real, dimension(3) fcoeff)
Give random distribution depending on position.
The original Nek5000 random number generator is implementted in ran1. This totally ad-hoc random number generator below could be preferable to the original one for the simple reason that it gives the same initial cindition independent of the number of processors, which is important for code verification.
Parameters
[in] ix,iy,iz GLL point index
[in] ieg global element number
[in] xl physical point coordinates
[in] fcoeff function coefficients
Returns
random distribution
Definition at line 54 of file math_tools.f.
math_ran_rng()
real function math_ran_rng (real lower, real upper)
Give random number in the defined range.
Parameters
[in] lower,upper range for random numer
Returns
random number in the defined range
Definition at line 81 of file math_tools.f.
References math_zbqlu01().
math_rot3da()
subroutine math_rot3da (real, dimension(ldim) vo, real, dimension(ldim) vi, real, dimension(ldim) va, real an)
3D rotation of a vector along given axis.
Parameters
[in] vo output vector
[in] vi input vector
[in] va rotation axis
[in] an rotation angle
Definition at line 331 of file math_tools.f.
References copy().
math_stepf()
real function math_stepf (real x)
Step function.
Continuous step function:
with and
Parameters
[in] x function argument
Returns
math_stepf
Definition at line 20 of file math_tools.f.
math_zbqlini()
subroutine math_zbqlini (integer seed)
Initialise Marsaglia-Zaman random number generator.
To initialise the random number generator - either repeatably or nonrepeatably.
Parameters
[in] seed number which generates elements of the array ZBQLIX
Todo:
Remove all common blocks and save variables to make it possible to be used by multiple tools
Definition at line 179 of file math_tools.f.
math_zbqlu01()
real function math_zbqlu01
Marsaglia-Zaman random number generator.
Returns a uniform random number between 0 & 1, using a Marsaglia-Zaman type subtract-with-borrow generator.
Remarks
Uses double precision, rather than integer, arithmetic throughout because MZ's INTEGER constants overflow 32-bit INTEGER storage (which goes from -2^31 to 2^31). Ideally, we would explicitly truncate all INTEGER quantities at each stage to ensure that the DOUBLE PRECISION representations DO not accumulate approximation error; however, on some machines the USE of DNINT to accomplish this is seriously slow (run-time increased by a factor of about 3). This DOUBLE PRECISION version has been tested against an INTEGER implementation that uses long integers (non-standard and, again, slow) - the output was identical up to the 16th decimal place after 10^10 calls, so we're probably OK ... In current implementation we follow Nek5000 compilation rulles prolonging all reals to doulbe with compiler flaggs.
Author
Richard Chandler (richa.nosp@m.rd@s.nosp@m.tats..nosp@m.ucl..nosp@m.ac.uk)
Paul Northrop (north.nosp@m.rop@.nosp@m.stats.nosp@m..ox..nosp@m.ac.uk)
Returns
random number
Todo:
Remove all common blocks and save variables to make it possible to be used by multiple tools
Definition at line 119 of file math_tools.f.