KTH framework for Nek5000 toolboxes; testing version: Checkpointing routines
Checkpointing routines
Framework for Nek5000 toolboxes » Toolbox » Input/output module
Checkpointing routines for toolbox.
Modules
Dummy checkpointing
Dummy routines for checkpointing.
Multistep checkpointing
Multistep checkpointing for DNS, MHD and linear simulations.
Files
file chkpt.f
Set of checkpoint routines.
Functions
subroutine chkpt_register ()
Register checkpointing module.
subroutine chkpt_init ()
Initilise checkpointing module.
logical function chkpt_is_initialised ()
Check if module was initialised.
subroutine chkpt_main
Main checkpoint interface.
subroutine chkpt_get_fset (step_cnt, set_out)
Get step count to the checkpoint and a set number.
Detailed Description
Checkpointing routines for toolbox.
This is the main interface to I/O checkpointing.
Module interface:
Global interface list:
Interface provided:
chkpt_register
chkpt_init
chkpt_is_initialised
chkpt_main
chkpt_get_fset
Global interface dependency:
Interface required:
multiple interfaces from Frame module, Runtime parameters and Monitoring module modules
chkpts_register; provided by submodule
chkpts_init; provided by submodule
chkpts_read; provided by submodule
chkpts_write; provided by submodule
Module interface usage:
!======================================================================
      subroutine userchk
      include 'TSTEP'
       if (istep.eq.0) then
!     start framework
         call frame_start
      endif
!     monitor simulation
      call frame_monitor
!     save/load files for full-restart
      call chkpt_main
!     finalise framework
      if (istep.eq.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     register modules
      call chkpt_register
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     initialise modules
      call chkpt_init
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      return
      end subroutine
!======================================================================
Module parameters:
Global parameter list:
Parameters provided by checkpoint module (include file - CHKPTD):
Varaible Type Runtime parameter Description
chpt_ifrst logical _chkpt:readchkpt start simulation form checkpoint
chpt_fnum integer _chkpt:chkpFnumber restart file number
chpt_step integer _chkpt:chkpInterval checkpiont dump frequency (number of time steps)
Module parameter usage:
[_CHKPT]
readchkpt = yes
chkpFnumber = 1
chkpInterval = 500
Function Documentation
chkpt_get_fset()
subroutine chkpt_get_fset (integer step_cnt, integer set_out)
Get step count to the checkpoint and a set number.
Parameters
[out] step_cnt decreasing step count in checkpoint writinh phase (otherwise -1)
[out] set_out set number
Definition at line 255 of file chkpt.f.
chkpt_init()
subroutine chkpt_init
Initilise checkpointing module.
Note
This routine should be called in frame_usr_init
Definition at line 86 of file chkpt.f.
References chkpts_init(), mntr_abort(), mntr_get_step_delay(), mntr_tmr_add(), mntr_warn(), and rprm_rp_get().
chkpt_is_initialised()
logical function chkpt_is_initialised
Check if module was initialised.
Returns
chkpt_is_initialised
Definition at line 185 of file chkpt.f.
chkpt_main()
subroutine chkpt_main
Main checkpoint interface.
Note
This routine should be called in userchk as a first framework call
Definition at line 200 of file chkpt.f.
References chkpts_read(), chkpts_write(), and mntr_get_step_delay().
chkpt_register()
subroutine chkpt_register
Register checkpointing module.
Note
This routine should be called in frame_usr_register
Definition at line 10 of file chkpt.f.
References chkpts_register(), mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_set_step_delay(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().