KTH framework for Nek5000 toolboxes; testing version: Power itertion routines
Power itertion routines
Framework for Nek5000 toolboxes » Toolbox » Tools module » Time stepper routines
Power iteration submodule.
Files
file pwit.f
Set of subroutines to perform power iterations within time stepper.
Functions
subroutine stepper_register ()
Register power iteration module.
subroutine stepper_init ()
Initilise power iteration module.
logical function stepper_is_initialised ()
Check if module was initialised.
subroutine stepper_vsolve
Renormalise vector and check convergence.
subroutine stepper_read (set_in)
Read restart files.
subroutine stepper_write
Write restart files.
Detailed Description
Power iteration submodule.
Power iteration submodule. This module is most useful for optimal initial condition mode. In case of the direct and adjoint modes it is better to perform simple linear simulation with a long time horison.
Todo:
Finish documentation
Module interface:
Global interface list:
Interface provided to tstpr:
stepper_register; provided for Time stepper routines
stepper_init; provided for Time stepper routines
stepper_vsolve; provided for Time stepper routines
Global interface dependency:
Interface required:
multiple interfaces from Runtime parameters and Monitoring module modules
chkpt_get_fset from Checkpointing routines module
chkptms_set_name, chkptms_restart_read and chkptms_restart_write from Multistep checkpointing module
cnht_opcmult, cnht_opcopy, cnht_opsub3 and cnht_glsc2_wt from Conjugated heat transfer tools module
Module parameters:
Global parameter list:
Parameters provided by pwit module (include file - PWITD):
Varaible Type Runtime parameter Description
pwit_l2n real _pwit:l2n initial L2 norm of the evolved vector for every cycle
Global parameter dependency:
Parameters required by power iteration module:
Checkpointing routines :
_chkpt:readchkpt
_chkpt:chkpFnumber
Nek5000 PARAM array and logical flags:
IFHEAT
Module parameter usage:
[_PWIT]              # Runtime paramere section for power iteration module
L2N                  = 0.10000000E+01         # Vector initial norm
Function Documentation
stepper_init()
subroutine stepper_init
Initilise power iteration module.
Note
This interface is called by tstpr_init
Definition at line 80 of file pwit.f.
References cmult(), cnht_opcmult(), cnht_opcopy(), mntr_abort(), mntr_check_abort(), mntr_log(), mntr_logr(), mntr_mod_is_name_reg(), mntr_tmr_add(), mntr_warn(), rprm_rp_get(), rprm_rp_is_name_reg(), rprm_sec_is_name_reg(), stepper_read(), and tstpr_dssum().
stepper_is_initialised()
logical function stepper_is_initialised
Check if module was initialised.
Returns
stepper_is_initialised
Definition at line 204 of file pwit.f.
References stepper_is_initialised().
stepper_read()
subroutine stepper_read (integer set_in)
Read restart files.
Parameters
[in] set_in restart set number
Definition at line 321 of file pwit.f.
References chkptms_restart_read(), chkptms_set_name(), io_init(), and mntr_log().
stepper_register()
subroutine stepper_register
Register power iteration module.
Note
This interface is called by tstpr_register
Definition at line 10 of file pwit.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
stepper_vsolve()
subroutine stepper_vsolve
Renormalise vector and check convergence.
Note
This interface is defined in tstpr_main
Remarks
This routine uses global scratch space SCRUZ
Definition at line 219 of file pwit.f.
References cmult(), cnht_opcmult(), cnht_opcopy(), cnht_opsub3(), mntr_log(), mntr_logr(), mntr_tmr_add(), outpost2(), stepper_write(), and tstpr_dssum().
stepper_write()
subroutine stepper_write
Write restart files.
Definition at line 364 of file pwit.f.
References chkpt_get_fset(), chkptms_restart_write(), chkptms_set_name(), io_init(), and mntr_log().