KTH framework for Nek5000 toolboxes; testing version: Conjugated heat transfer tools
Conjugated heat transfer tools
Framework for Nek5000 toolboxes » Toolbox » Utility module
Conjugated heat transfer tools.
Files
file cnht_tools.f
Set of utilities related to conjugated heat transfer to build single scalar product for velocity nad temperature.
Functions
subroutine cnht_register ()
Register conjugated heat transfer tools module.
subroutine cnht_init ()
Initilise conjugated heat transfer tools module.
logical function cnht_is_initialised ()
Check if module was initialised.
subroutine cnht_forcing (ffx, ffy, ffz, ix, iy, iz, ieg)
Calcualte forcing ralted to conjugated heat transfer.
subroutine cnht_cpfld_set ()
Set cpfld coefficient for given type of simulation.
subroutine cnht_oprzero (a1, a2, a3, a4)
Zero velocity and temperature vectors.
subroutine cnht_opcopy (a1, a2, a3, a4, b1, b2, b3, b4)
Copy vectors A=B (velocity and temperature)
subroutine cnht_opadd2 (a1, a2, a3, a4, b1, b2, b3, b4)
Add velocity and temperature vectors A = A+B.
subroutine cnht_opsub2 (a1, a2, a3, a4, b1, b2, b3, b4)
Subtract vectors A = A-B (velocity and temperature)
subroutine cnht_opsub3 (a1, a2, a3, a4, b1, b2, b3, b4, c1, c2, c3, c4)
Subtract vectors A = B-C (velocity and temperature)
subroutine cnht_opcmult (a1, a2, a3, a4, const)
Multiply vector by constant A = c*A (single coeff. for velocity and temperature)
subroutine cnht_opcmult2c (a1, a2, a3, a4, const1, const2)
Multiply vector by constant A = c*A with separate const. for velocity and temperature.
subroutine cnht_opadd2cm (a1, a2, a3, a4, b1, b2, b3, b4, coeff)
Vector summation with scaling A = A+c*B (velocity and temperature)
subroutine cnht_opsub2cm (a1, a2, a3, a4, b1, b2, b3, b4, coeff)
Vector subtraction with scaling A = A-c*B (velocity and temperature)
subroutine cnht_weight_fun (lvx, lvy, lvz, lt, coeff)
Weigth velocity and temperature fields.
real function cnht_glsc2_wt (b1, b2, b3, b4, x1, x2, x3, x4, wt)
Global inner product of velocity and temperature fields.
Detailed Description
Conjugated heat transfer tools.
Set of utilities related to conjugated heat transfer to build single scalar product for velocity nad temperature. This module is automatically registered by Time stepper routines module.
Todo:
Complete documentation
Module interface:
Global interface list:
Interface provided:
cnht_register
cnht_init
cnht_is_initialised
cnht_forcing
cnht_cpfld_set
cnht_oprzero
cnht_opcopy
cnht_opadd2
cnht_opsub2
cnht_opsub3
cnht_opcmult
cnht_opcmult2c
cnht_opadd2cm
cnht_opsub2cm
cnht_weight_fun
cnht_glsc2_wt
Global interface dependency:
Interface required:
multiple interfaces from Runtime parameters and Monitoring module modules
Module parameters:
Global parameter list:
Parameters provided by time snht module (include file - CNHTD):
Varaible Type Runtime parameter Description
cnht_sc real _cnht:scln norm scaling factor
cnht_sv real _cnht:sclv velocity scaling factor (Pareto curve)
cnht_st real _cnht:sclt temperature scaling factor (Pareto curve)
cnht_gx real _cnht:grx X component of gravitational field
cnht_gy real _cnht:gry Y component of gravitational field
cnht_gz real _cnht:grz Z component of gravitational field
Module parameters:
Global parameter dependency:
Parameters required by time stepper module:
Nek5000 PARAM array
PARAM(1)
PARAM(2)
Module parameter usage:
[_CNHT]               # Runtime paramere section for conj. heat trans. tool module
SCLN                 = 0.33655800E+01         # Norm scaling factor
SCLV                 = 0.50000000E+00         # Velocity scaling factor (Pareto curve)
SCLT                 = 0.50000000E+00         # Temperature scaling factor (Pareto curve)
GRX                  = 0.00000000E+00         # X component of gravitational field
GRY                  = 0.10000000E+01         # Y component of gravitational field
Function Documentation
cnht_cpfld_set()
subroutine cnht_cpfld_set
Set cpfld coefficient for given type of simulation.
Definition at line 205 of file cnht_tools.f.
cnht_forcing()
subroutine cnht_forcing (real ffx, real ffy, real ffz, integer ix, integer iy, integer iz, integer ieg)
Calcualte forcing ralted to conjugated heat transfer.
Parameters
[in,out] ffx,ffy,ffz forcing; x,y,z component
[in] ix,iy,iz GLL point index
[in] ieg global element number
Definition at line 159 of file cnht_tools.f.
References gllel().
cnht_glsc2_wt()
real function cnht_glsc2_wt (real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real, dimension(1) x1, real, dimension(1) x2, real, dimension(1) x3, real, dimension(1) x4, real, dimension(1) wt)
Global inner product of velocity and temperature fields.
Parameters
[in] b1,b2,b3 vlocity field 1
[in] b4 temperature field 1
[in] x1,x2,x3 vlocity field 2
[in] x4 temperature field 2
[in] wt mass matrix
Returns
cnht_glsc2_wt
Definition at line 589 of file cnht_tools.f.
References glsum().
cnht_init()
subroutine cnht_init
Initilise conjugated heat transfer tools module.
Note
This routine should be called in frame_usr_init
Definition at line 81 of file cnht_tools.f.
References gradm1(), mntr_warn(), and rprm_rp_get().
cnht_is_initialised()
logical function cnht_is_initialised
Check if module was initialised.
Returns
cnht_is_initialised
Definition at line 143 of file cnht_tools.f.
cnht_opadd2()
subroutine cnht_opadd2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4)
Add velocity and temperature vectors A = A+B.
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
Definition at line 309 of file cnht_tools.f.
References add2().
cnht_opadd2cm()
subroutine cnht_opadd2cm (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real coeff)
Vector summation with scaling A = A+c*B (velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
[in] coeff scaling coefficient
Definition at line 468 of file cnht_tools.f.
cnht_opcmult()
subroutine cnht_opcmult (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real const)
Multiply vector by constant A = c*A (single coeff. for velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity fields
[in,out] a4 temperature field
[in] const coefficient
Definition at line 404 of file cnht_tools.f.
References cmult().
cnht_opcmult2c()
subroutine cnht_opcmult2c (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real const1, real const2)
Multiply vector by constant A = c*A with separate const. for velocity and temperature.
Parameters
[in,out] a1,a2,a3 vlocity fields
[in,out] a4 temperature field
[in] const1 velocity coefficient
[in] const2 temperature coefficient
Definition at line 436 of file cnht_tools.f.
References cmult().
cnht_opcopy()
subroutine cnht_opcopy (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4)
Copy vectors A=B (velocity and temperature)
Parameters
[out] a1,a2,a3 vlocity field 1
[out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
Definition at line 278 of file cnht_tools.f.
References copy().
cnht_oprzero()
subroutine cnht_oprzero (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4)
Zero velocity and temperature vectors.
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
Definition at line 248 of file cnht_tools.f.
References rzero().
cnht_opsub2()
subroutine cnht_opsub2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4)
Subtract vectors A = A-B (velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
Definition at line 340 of file cnht_tools.f.
References sub2().
cnht_opsub2cm()
subroutine cnht_opsub2cm (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real coeff)
Vector subtraction with scaling A = A-c*B (velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
[in] coeff scaling coefficient
Definition at line 514 of file cnht_tools.f.
cnht_opsub3()
subroutine cnht_opsub3 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real, dimension(1) c1, real, dimension(1) c2, real, dimension(1) c3, real, dimension(1) c4)
Subtract vectors A = B-C (velocity and temperature)
Parameters
[out] a1,a2,a3 vlocity field 1
[out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
[in] c1,c2,c3 vlocity field 3
[in] c4 temperature field 3
Definition at line 373 of file cnht_tools.f.
References sub3().
cnht_register()
subroutine cnht_register
Register conjugated heat transfer tools module.
Note
This routine should be called in frame_usr_register
Definition at line 11 of file cnht_tools.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
cnht_weight_fun()
subroutine cnht_weight_fun (real, dimension(1) lvx, real, dimension(1) lvy, real, dimension(1) lvz, real, dimension(1) lt, real coeff)
Weigth velocity and temperature fields.
Parameters
[in,out] lvx,lvy,lvz vlocity fields
[in,out] lt temperature field
[in] coeff scaling coefficient
Definition at line 558 of file cnht_tools.f.
References cnht_opcmult2c().