KTH framework for Nek5000 toolboxes; testing version: Post-processing of 3D statistics
Post-processing of 3D statistics
Framework for Nek5000 toolboxes » Toolbox » Post processing tools
Set of post-processing routines for 3D statistics.
Files
file pstat3D.f
Post processing for statistics module.
file pstat3D_IO.f
Post processing I/O routines for statistics module.
Functions
subroutine pstat3d_register ()
Register post processing statistics module.
subroutine pstat3d_init ()
Initilise pstat module.
logical function pstat3d_is_initialised ()
Check if module was initialised.
subroutine pstat3d_main
Main interface of pstat module.
subroutine pstat3d_sts_avg
Read in fields and average them.
subroutine pstat3d_nfield
Calculate new fileds.
subroutine pstat3d_interp
Interpolate int the set of points.
subroutine pstat3d_mfo
Write field data data to the file.
subroutine pstat3d_mfi_interp
Read interpolation points position and redistribute them.
subroutine pstat3d_mfo_interp
Geather data and write it down.
subroutine pstat3d_field_out (int_field, fldim, ierr)
Geather single field data and write it down.
Detailed Description
Set of post-processing routines for 3D statistics.
This tools allows post-processing of 3D statistics files generated by the stats tool. In particular, it allows to do two things:
average across previously generated 3D statistics files, i.e. with prefixes s01 to s11 to generate a single set of corresponding files.
Interpolate this averaged data at arbitrary points and store the results in a single file that can be easily read using e.g. Python.
In addition, when doing the above the tool will compute a number of extra fields, including the components of the turbulent kinetic energy budget. Details below.
The following workflow is suggested to use the module:
Create a new case directory with the same geometry as your main case.
Set up the .usr and .par and makefile_usr.inc files according to the examples herein. (See also the phill_PSTAT3D example case.) Compile the case.
Create a folder called DATA in the case directory.
Copy the previously generated files with prefex s01-s11 to this folder. If you are not interested in point interpolation the next 2 steps can be skipped.
Create the file int_pos using the Python API in writer_int_pos.py. This file will contain the locations of the points, to which the average data will be interpolated.
Move the int_pos file to the DATA folder.
Run the case. If you are not using point interpolation, the case will eventually "crash" because no int_pos file will be found. That is OK.
As a result, the tool will produce a set of files with prefix a01 to a22 containing data averaged across STS_NFILE of the provided s01-s11 files, excluding those collected at times less than STS_STIME. The list of fields and their distributon acros the files is given in field_list.txt in this folder.
The interpolated point data is saved to a file called int_fld. It can be read using the functions in reader_int_fld.py Python file.
List of fields generated by the PSTAT3D tool and their distributon
across files prefixed a01 to a22.
The following nomenclature is adopted for the terms in the transport equations
for Reynolds stresses.
P - production
D - dissipation
VD - viscous diffusion
C - convection
T - turbulent transport
Pi - pressure-velocity-gradient tensor
PT - pressure transport
PS - pressure strain
See eqs. (5)-(12) in https://publications.anl.gov/anlpubs/2017/03/133610.pdf
for exact definition
"k" indicates the corresponding term in the kinetic energy equation, e.g.
Pk - production of k.
Please observe that <uu> stands for <u'u'> since the mean has been already subtracted.
- a01
    <u>
    <v>
    <w>
    <uu>
- a02
    <vv>
    <ww>
    <uv>
    <uw>
- a03
    <vw>
    <p>
    <pp>
    <ppp>
- a04
    <pppp>
    <uuu>
    <vvv>
    <www>
- a05
    <uuv>
    <uuw>
    <uvv>
    <vvw>
- a06
    <uww>
    <vww>
    <uvw>
    Pxx
- a07
    Pyy
    Pzz
    Pxy
    Pxz
- a08
    Pyz
    Dxx
    Dyy
    Dzz
- a09
    Dxy
    Dxz
    Dyz
    Txx
- a10
    Tyy
    Tzz
    Txy
    Txz
- a11
    Tyz
    VDxx
    VDyy
    VDzz
- a12
    VDxy
    VDxz
    VDyz
    Pixx
- a13
    Piyy
    Pizz
    Pixy
    Pixz
- a14
    Piyz
    Cxx
    Cyy
    Czz
- a15
    Cxy
    Cxz
    Cyz
    Pk
- a16
    Dk
    Tk
    VDk
    Pik
- a17
    Ck
    Resk (Residual from all the terms)
    PTxx
    PTyy
- a18
    PTzz
    PTxy
    PTxz
    PTyz
- a19
    PSxx
    PSyy
    PSzz
    PSxy
- a20
    PSxz
    PTyz
    <du/dx>
    <du/dy>
- a21
    <du/dz>
    <du/dx>
    <dv/dy>
    <dv/dz>
- a22
    <dw/dx>
    <dw/dy>
    <dw/dz>
    Tk
Module interface:
Global interface list:
pstat3d_register
pstat3d_init
pstat3d_main
Global interface dependency:
Interface required:
multiple interfaces from Runtime parameters and Monitoring module modules
io_mfo_fname from Input/output module module
io_file_freeid from Input/output module module (debugging only)
Module interface usage:
!======================================================================
      subroutine userchk
      include 'TSTEP'
      if (istep.eq.0) then
!     start framework
         call frame_start
      endif
!     monitor simulation
      call frame_monitor
!     collect statistics
      call pstat3d_main()
!     Force running for only one iteration
      lastep=1
!     finalise framework
      if (istep.eq.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      ! register modules
      call pstat3d_register
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      ! initialise modules
      call pstat3d_init
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      return
      end subroutine
!======================================================================
Module parameters:
Global parameter list:
Parameters provided by pstat3d module (include file - PSTAT3D):
Varaible Type Runtime parameter Description
pstat_nfile integer _pstat3d:STS_NFILE Number of collected s01-s11 files
pstat_stime float _pstat3d:STS_STIME Statistics starting time
pstat_nstep integer _pstat3d:STS_NSTEP Number of steps between averaging in collected s01-s11 files
Module parameter usage:
[_PSTAT3D]                # Runtime paramere section for pstat module
STS_NFILE            = 2                      # Number of collected s01-s11 files
STS_STIME            = 0.69968783E+02         # Statistics starting time
STS_NSTEP            = 10                     # Number of steps between averaging in collected s01-s11 files
Function Documentation
pstat3d_field_out()
subroutine pstat3d_field_out (real, dimension(fldim*lhis) int_field, integer fldim, integer ierr)
Geather single field data and write it down.
Parameters
[in] int_field interpolated field
[in] fldim field dimension
[out] ierr error flag
Definition at line 588 of file pstat3D_IO.f.
References byte_write, copy(), copyx4(), crecv2(), and csend().
pstat3d_init()
subroutine pstat3d_init
Initilise pstat module.
Note
This routine should be called in frame_usr_init
Definition at line 95 of file pstat3D.f.
References icopy(), mntr_tmr_add(), mntr_warn(), and rprm_rp_get().
pstat3d_interp()
subroutine pstat3d_interp
Interpolate int the set of points.
Definition at line 790 of file pstat3D.f.
References io_file_freeid(), mntr_abort(), pstat3d_mfi_interp(), and pstat3d_mfo_interp().
pstat3d_is_initialised()
logical function pstat3d_is_initialised
Check if module was initialised.
Returns
pstat3d_is_initialised
Definition at line 160 of file pstat3D.f.
pstat3d_main()
subroutine pstat3d_main
Main interface of pstat module.
Definition at line 173 of file pstat3D.f.
References mntr_log(), mntr_tmr_add(), pstat3d_interp(), pstat3d_nfield(), and pstat3d_sts_avg().
pstat3d_mfi_interp()
subroutine pstat3d_mfi_interp
Read interpolation points position and redistribute them.
Definition at line 82 of file pstat3D_IO.f.
References bcast(), blank(), byte_close, byte_open, byte_read, byte_reverse, byte_reverse8, copy(), copy4r(), crecv2(), csend(), io_file_freeid(), mntr_check_abort(), and mntr_logi().
pstat3d_mfo()
subroutine pstat3d_mfo
Write field data data to the file.
Definition at line 9 of file pstat3D_IO.f.
References outpost().
pstat3d_mfo_interp()
subroutine pstat3d_mfo_interp
Geather data and write it down.
Definition at line 275 of file pstat3D_IO.f.
References byte_close, byte_open, byte_write, mntr_check_abort(), and pstat3d_field_out().
pstat3d_nfield()
subroutine pstat3d_nfield
Calculate new fileds.
Definition at line 353 of file pstat3D.f.
References add2(), add3(), add4(), admcol3(), chsign(), cmult(), col3(), copy(), gradm1(), pstat3d_mfo(), rzero(), sub2(), sub3(), subcol3(), subcol4(), and vdot3().
pstat3d_register()
subroutine pstat3d_register
Register post processing statistics module.
Note
This routine should be called in frame_usr_register
Definition at line 10 of file pstat3D.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
pstat3d_sts_avg()
subroutine pstat3d_sts_avg
Read in fields and average them.
Definition at line 215 of file pstat3D.f.
References add2s2(), addfid(), cmult(), io_init(), io_mfo_fname(), mfi(), outpost(), and rzero().