KTH framework for Nek5000 toolboxes; testing version: Frame module
Frame module
Framework for Nek5000 toolboxes » Toolbox » Driver module
Backbone for toolboxes.
Modules
Monitoring module
Monitoring routines for toolboxes.
Runtime parameters
Routines related to module's runtime parameters.
Files
file frame.f
Set of routines for framework operation.
Functions
subroutine frame_start
Start framework.
subroutine frame_monitor
Simulataion monitoring.
subroutine frame_end
Finalise framework.
integer function frame_get_master ()
Specify master node id.
Detailed Description
Backbone for toolboxes.
The frame module provides backbone of the whole framework consisting of dynamical (as much as fortran 77 allows for it) databases for registered modules, runtime parameters and timers. This is supposed to simplify interactions between different modules, logging and operations on runtime parameters. It provides interfaces for intialisation, monitoring and finalisation of the framework. It requires as well three subroutines defined in setup.usr and providing modules registration (frame_usr_register), initialisation (frame_usr_init) and finalisation (frame_usr_end). There are three modules automatically started by framework: monitor, runtime parameters and I/O tools. These modules should not be registered inside (frame_usr_register).
This module also provides an include file FRAMELP defining log priorities and runtime parameter types. Using logging routines from the monitor submodule, one can easily specify the verbosity of the code. The logging level can be set in two ways: by LOGLEVEL runtime parameter in [_MNTR] section of setup.par file (doeas not cover framework initialisation) or by setting the enviromental variable FRAMELOGL. The second way covers all stages of the simulation. For the bash shell this variable can be set by:
FRAMELOGL = 5
export FRAMELOGL
Module interface:
Global interface list:
Interface provided:
frame_start
frame_monitor
frame_end
frame_get_master
Global interface dependency:
Interface required:
multiple interfaces from Runtime parameters and Monitoring module modules (automatically registered)
io_file_close from I/O tools module (automatically registered)
frame_usr_register; user defined
frame_usr_init; user defined
frame_usr_end; user defined
Module interface usage:
!======================================================================
      subroutine userchk
      include 'TSTEP'
      if (istep.eq.0) then
!     start framework
         call frame_start
      endif
!     monitor simulation
      call frame_monitor
!     place other modules calls
!     finalise framework
      if (istep.eq.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
!=======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     register modules
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     initialise modules
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     finalise modules
      return
      end subroutine
!======================================================================
Function Documentation
frame_end()
subroutine frame_end
Finalise framework.
Definition at line 75 of file frame.f.
References io_file_close(), and mntr_tmr_summary_print().
frame_get_master()
integer function frame_get_master
Specify master node id.
Returns
frame_get_master
Definition at line 97 of file frame.f.
frame_monitor()
subroutine frame_monitor
Simulataion monitoring.
Definition at line 58 of file frame.f.
References mntr_wclock().
frame_start()
subroutine frame_start
Start framework.
Note
This routine requires frame_usr_register and frame_usr_init to be defined in setup.usr
Definition at line 11 of file frame.f.
References bcast(), io_register(), mntr_init(), mntr_register_mod(), mntr_register_par(), rprm_dict_get(), rprm_init(), and rprm_register().