KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/hsmg.f File Reference
hsmg.f File Reference
Functions/Subroutines
subroutine hsmg_setup ()
subroutine hsmg_setup_semhat
subroutine hsmg_setup_intp
subroutine hsmg_setup_intpm (jh, zf, zc, nf, nc)
subroutine hsmg_setup_dssum
subroutine h1mg_setup_wtmask
subroutine hsmg_setup_wtmask
subroutine hsmg_intp (uf, uc, l)
subroutine hsmg_rstr (uc, uf, l)
subroutine hsmg_rstr_no_dssum (uc, uf, l)
subroutine hsmg_tnsr (v, nv, u, nu, A, At)
subroutine hsmg_tnsr2d (v, nv, u, nu, A, Bt)
subroutine hsmg_tnsr3d (v, nv, u, nu, A, Bt, Ct)
subroutine hsmg_tnsr2d_el (v, nv, u, nu, A, Bt)
subroutine hsmg_tnsr3d_el (v, nv, u, nu, A, Bt, Ct)
subroutine hsmg_dssum (u, l)
subroutine hsmg_dsprod (u, l)
subroutine hsmg_schwarz_dssum (u, l)
subroutine hsmg_extrude (arr1, l1, f1, arr2, l2, f2, nx, ny, nz)
subroutine h1mg_schwarz (e, r, sigma, l)
subroutine h1mg_schwarz_part1 (e, r, l)
subroutine hsmg_schwarz (e, r, l)
subroutine hsmg_schwarz_toext2d (a, b, n)
subroutine hsmg_schwarz_toext3d (a, b, n)
subroutine hsmg_schwarz_toreg2d (b, a, n)
subroutine hsmg_schwarz_toreg3d (b, a, n)
subroutine h1mg_setup_fdm ()
subroutine hsmg_setup_fdm ()
subroutine hsmg_setup_fast (s, d, nl, ah, bh, n)
subroutine hsmg_setup_fast1d (s, lam, nl, lbc, rbc, ll, lm, lr, ah, bh, n, ie)
subroutine hsmg_setup_fast1d_a (a, lbc, rbc, ll, lm, lr, ah, n)
subroutine hsmg_setup_fast1d_b (b, lbc, rbc, ll, lm, lr, bh, n)
subroutine hsmg_fdm (e, r, l)
subroutine hsmg_do_fast (e, r, s, d, nl)
subroutine hsmg_do_wt (u, wt, nx, ny, nz)
subroutine hsmg_setup_rstr_wt (wt, nx, ny, nz, l, w)
subroutine hsmg_setup_mask (wt, nx, ny, nz, l, w)
subroutine hsmg_setup_schwarz_wt (ifsqrt)
subroutine h1mg_setup_schwarz_wt (ifsqrt)
subroutine hsmg_schwarz_wt (e, l)
subroutine hsmg_schwarz_wt2d (e, wt, n)
subroutine hsmg_schwarz_wt3d (e, wt, n)
subroutine hsmg_coarse_solve (e, r)
subroutine hsmg_setup_solve
subroutine hsmg_solve (e, r)
subroutine hsmg_setup_mg_nx ()
subroutine hsmg_index_0
subroutine outfldn (x, n, txt10, ichk)
subroutine outfldn0 (x, n, txt10, ichk)
subroutine outflda (x, n, txt10, ichk)
subroutine outfldan (x, n, txt10, ichk)
subroutine h1mg_solve (z, rhs, if_hybrid)
subroutine h1mg_axm (w, p, aw, ap, l, wk)
subroutine h1mg_axml (w, p, h1, h2, nx, ny, nz, nel, g, ng, b, mask, ifh2)
subroutine h1mg_mask (w, mask, nel)
subroutine mg_mask_e (w, mask)
subroutine axe (w, p, h1, h2, g, ng, b, nx, ny, nz, ur, us, ut, ifh2, ifrz, e)
subroutine hsmg_tnsr1 (v, nv, nu, A, At)
subroutine hsmg_tnsr1_2d (v, nv, nu, A, Bt)
subroutine hsmg_tnsr1_3d (v, nv, nu, A, Bt, Ct)
subroutine h1mg_rstr (r, l, ifdssum)
subroutine h1mg_setup ()
subroutine h1mg_setup_mg_nx ()
subroutine h1mg_setup_semhat
subroutine h1mg_setup_dssum
subroutine mg_set_msk (p_msk, l0)
subroutine h1mg_setup_mask (mask, nm, nx, ny, nz, nel, l, w)
subroutine mg_set_h1 (p_h1, l0)
subroutine mg_set_h2 (p_h2, l0)
subroutine hsmg_intp_fc (uc, uf, l)
subroutine mg_intp_fc_e (uc, uf, nxc, nyc, nzc, nxf, nyf, nzf, e, l, w)
subroutine mg_intp_gfc_e (gc, gf, ng, nxc, nyc, nzc, nxf, nyf, nzf, e, l, w)
subroutine mg_scale_mass (b, g, wt, ng, nx, ny, nz, wk, ifinv)
subroutine mg_set_gb (p_g, p_b, l0)
subroutine gxfer_e (g, ng, e)
subroutine chkr (name3, ii)
subroutine outgmat (a, ng, nx, ny, name6, k, e)
subroutine outmatz (a, m, n, name6, ie)
subroutine h1mg_setup_schwarz_wt_2 (wt, ie, n, work, ifsqrt)
subroutine h1mg_setup_schwarz_wt2d_2 (wt, ie, n, work, ifsqrt)
subroutine h1mg_setup_schwarz_wt3d_2 (wt, ie, n, work, ifsqrt)
subroutine h1mg_setup_schwarz_wt_1 (wt, l, ifsqrt)
Function/Subroutine Documentation
axe()
subroutine axe (real, dimension (nx*ny*nz) w, real, dimension (nx*ny*nz) p, real, dimension(nx*ny*nz) h1, real, dimension(nx*ny*nz) h2, real, dimension (ng,nx*ny*nz) g, ng, real, dimension (nx*ny*nz) b, nx, ny, nz, real, dimension(nx*ny*nz) ur, real, dimension(nx*ny*nz) us, real, dimension(nx*ny*nz) ut, logical ifh2, logical ifrz, integer e)
Definition at line 2073 of file hsmg.f.
References exitti(), gradl_rst(), and gradl_rst_t().
chkr()
subroutine chkr (character*3 name3, ii)
Definition at line 2893 of file hsmg.f.
gxfer_e()
subroutine gxfer_e (real, dimension(ng,1) g, ng, integer e)
Definition at line 2862 of file hsmg.f.
h1mg_axm()
subroutine h1mg_axm (real, dimension(1) w, real, dimension(1) p, aw, ap, l, real, dimension(1) wk)
Definition at line 1951 of file hsmg.f.
References add2sxy(), h1mg_axml(), hsmg_dssum(), mg_set_gb(), mg_set_h1(), mg_set_h2(), and mg_set_msk().
h1mg_axml()
subroutine h1mg_axml (real, dimension (nx*ny*nz,nel) w, real, dimension (nx*ny*nz,nel) p, real, dimension(nx*ny*nz,nel) h1, real, dimension(nx*ny*nz,nel) h2, nx, ny, nz, nel, real, dimension (ng*nx*ny*nz,nel) g, ng, real, dimension (nx*ny*nz,nel) b, integer, dimension(1) mask, logical ifh2)
Definition at line 2005 of file hsmg.f.
References axe(), and mg_mask_e().
h1mg_mask()
subroutine h1mg_mask (real, dimension (1) w, integer, dimension(1) mask, nel)
Definition at line 2044 of file hsmg.f.
References mg_mask_e().
h1mg_rstr()
subroutine h1mg_rstr (real, dimension(1) r, integer l, logical ifdssum)
Definition at line 2216 of file hsmg.f.
References hsmg_do_wt(), hsmg_dssum(), and hsmg_tnsr1().
h1mg_schwarz()
subroutine h1mg_schwarz (real, dimension(1) e, real, dimension(1) r, sigma, l)
Definition at line 425 of file hsmg.f.
References cmult(), h1mg_schwarz_part1(), and hsmg_schwarz_wt().
h1mg_schwarz_part1()
subroutine h1mg_schwarz_part1 (real, dimension(1) e, real, dimension(1) r, l)
Definition at line 440 of file hsmg.f.
References h1mg_mask(), hsmg_dssum(), hsmg_extrude(), hsmg_fdm(), hsmg_schwarz_dssum(), hsmg_schwarz_toext2d(), hsmg_schwarz_toext3d(), hsmg_schwarz_toreg2d(), and hsmg_schwarz_toreg3d().
h1mg_setup()
subroutine h1mg_setup
Definition at line 2234 of file hsmg.f.
References geom_reset(), h1mg_setup_dssum(), h1mg_setup_fdm(), h1mg_setup_mg_nx(), h1mg_setup_schwarz_wt(), h1mg_setup_semhat(), h1mg_setup_wtmask(), hsmg_setup_intp(), hsmg_setup_solve(), mg_set_gb(), mg_set_h1(), mg_set_h2(), mg_set_msk(), rone(), and rzero().
h1mg_setup_dssum()
subroutine h1mg_setup_dssum
Definition at line 2361 of file hsmg.f.
References get_vert(), and setupds().
h1mg_setup_fdm()
subroutine h1mg_setup_fdm
Definition at line 633 of file hsmg.f.
References exitt(), and hsmg_setup_fast().
h1mg_setup_mask()
subroutine h1mg_setup_mask (integer, dimension(1) mask, nm, integer nx, integer ny, integer nz, nel, integer l, real, dimension(nx,ny,nz,nel) w)
Definition at line 2426 of file hsmg.f.
References exitti(), facev(), get_fast_bc(), hsmg_dsprod(), iglmax(), and rone().
h1mg_setup_mg_nx()
subroutine h1mg_setup_mg_nx
Definition at line 2272 of file hsmg.f.
h1mg_setup_schwarz_wt()
subroutine h1mg_setup_schwarz_wt (logical ifsqrt)
Definition at line 1217 of file hsmg.f.
References exitt(), and h1mg_setup_schwarz_wt_1().
h1mg_setup_schwarz_wt2d_2()
subroutine h1mg_setup_schwarz_wt2d_2 (real, dimension(n,4,2,nelv) wt, integer ie, integer n, real, dimension(n,n) work, logical ifsqrt)
Definition at line 2965 of file hsmg.f.
h1mg_setup_schwarz_wt3d_2()
subroutine h1mg_setup_schwarz_wt3d_2 (real, dimension(n,n,4,3,nelv) wt, integer ie, integer n, real, dimension(n,n,n) work, logical ifsqrt)
Definition at line 2998 of file hsmg.f.
h1mg_setup_schwarz_wt_1()
subroutine h1mg_setup_schwarz_wt_1 (real, dimension(1) wt, l, logical ifsqrt)
Definition at line 3048 of file hsmg.f.
References h1mg_setup_schwarz_wt_2(), hsmg_dssum(), hsmg_extrude(), hsmg_schwarz_dssum(), hsmg_schwarz_toreg2d(), hsmg_schwarz_toreg3d(), and rone().
h1mg_setup_schwarz_wt_2()
subroutine h1mg_setup_schwarz_wt_2 (real, dimension(1) wt, ie, n, real, dimension(1) work, logical ifsqrt)
Definition at line 2954 of file hsmg.f.
References h1mg_setup_schwarz_wt2d_2(), and h1mg_setup_schwarz_wt3d_2().
h1mg_setup_semhat()
subroutine h1mg_setup_semhat
Definition at line 2340 of file hsmg.f.
References copy(), semhat(), and transpose().
h1mg_setup_wtmask()
subroutine h1mg_setup_wtmask
Definition at line 157 of file hsmg.f.
References exitt(), hsmg_setup_mask(), and hsmg_setup_rstr_wt().
h1mg_solve()
subroutine h1mg_solve (real, dimension(1) z, real, dimension(1) rhs, logical if_hybrid)
Definition at line 1855 of file hsmg.f.
References copy(), dsavg(), h1mg_axm(), h1mg_mask(), h1mg_rstr(), h1mg_schwarz(), hsmg_coarse_solve(), and hsmg_intp().
hsmg_coarse_solve()
subroutine hsmg_coarse_solve (real, dimension(1) e, real, dimension(1) r)
Definition at line 1321 of file hsmg.f.
References dnekclock(), and nekgsync().
hsmg_do_fast()
subroutine hsmg_do_fast (real, dimension(nl**ldim,nelv) e, real, dimension(nl**ldim,nelv) r, real, dimension(nl*nl,2,ldim,nelv) s, real, dimension(nl**ldim,nelv) d, nl)
Definition at line 897 of file hsmg.f.
References hsmg_tnsr2d_el(), and hsmg_tnsr3d_el().
hsmg_do_wt()
subroutine hsmg_do_wt (real, dimension(nx,ny,nz,nelv) u, real, dimension(nx,nz,2,ldim,nelv) wt, integer nx, integer ny, integer nz)
Definition at line 932 of file hsmg.f.
hsmg_dsprod()
subroutine hsmg_dsprod (real, dimension(1) u, l)
Definition at line 342 of file hsmg.f.
References nekgsync().
hsmg_dssum()
subroutine hsmg_dssum (real, dimension(1) u, l)
Definition at line 326 of file hsmg.f.
References dnekclock(), and nekgsync().
hsmg_extrude()
subroutine hsmg_extrude (real, dimension(nx,ny,nz,nelv) arr1, integer l1, real f1, real, dimension(nx,ny,nz,nelv) arr2, integer l2, real f2, integer nx, integer ny, integer nz)
Definition at line 368 of file hsmg.f.
hsmg_fdm()
subroutine hsmg_fdm (e, r, l)
Definition at line 885 of file hsmg.f.
References hsmg_do_fast().
hsmg_index_0()
subroutine hsmg_index_0
Definition at line 1663 of file hsmg.f.
References izero().
hsmg_intp()
subroutine hsmg_intp (real, dimension(1) uf, real, dimension(1) uc, integer l)
Definition at line 205 of file hsmg.f.
References hsmg_tnsr().
hsmg_intp_fc()
subroutine hsmg_intp_fc (real, dimension(1) uc, real, dimension(1) uf, l)
Definition at line 2589 of file hsmg.f.
References hsmg_tnsr().
hsmg_rstr()
subroutine hsmg_rstr (real, dimension(1) uc, real, dimension(1) uf, integer l)
Definition at line 214 of file hsmg.f.
References hsmg_do_wt(), hsmg_dssum(), and hsmg_tnsr().
hsmg_rstr_no_dssum()
subroutine hsmg_rstr_no_dssum (real, dimension(1) uc, real, dimension(1) uf, integer l)
Definition at line 227 of file hsmg.f.
References hsmg_do_wt(), and hsmg_tnsr().
hsmg_schwarz()
subroutine hsmg_schwarz (real, dimension(1) e, real, dimension(1) r, integer l)
Definition at line 496 of file hsmg.f.
References hsmg_do_wt(), hsmg_dssum(), hsmg_extrude(), hsmg_fdm(), hsmg_schwarz_dssum(), hsmg_schwarz_toext2d(), hsmg_schwarz_toext3d(), hsmg_schwarz_toreg2d(), and hsmg_schwarz_toreg3d().
hsmg_schwarz_dssum()
subroutine hsmg_schwarz_dssum (u, l)
Definition at line 354 of file hsmg.f.
References dnekclock(), and nekgsync().
hsmg_schwarz_toext2d()
subroutine hsmg_schwarz_toext2d (real, dimension(0:n+1,0:n+1,nelv) a, real, dimension(n,n,nelv) b, integer n)
Definition at line 555 of file hsmg.f.
hsmg_schwarz_toext3d()
subroutine hsmg_schwarz_toext3d (real, dimension(0:n+1,0:n+1,0:n+1,nelv) a, real, dimension(n,n,n,nelv) b, integer n)
Definition at line 580 of file hsmg.f.
References rzero().
hsmg_schwarz_toreg2d()
subroutine hsmg_schwarz_toreg2d (real, dimension(n,n,nelv) b, real, dimension(0:n+1,0:n+1,nelv) a, integer n)
Definition at line 599 of file hsmg.f.
hsmg_schwarz_toreg3d()
subroutine hsmg_schwarz_toreg3d (real, dimension(n,n,n,nelv) b, real, dimension(0:n+1,0:n+1,0:n+1,nelv) a, integer n)
Definition at line 615 of file hsmg.f.
hsmg_schwarz_wt()
subroutine hsmg_schwarz_wt (e, l)
Definition at line 1249 of file hsmg.f.
References hsmg_schwarz_wt2d(), and hsmg_schwarz_wt3d().
hsmg_schwarz_wt2d()
subroutine hsmg_schwarz_wt2d (real, dimension(n,n,nelv) e, real, dimension(n,4,2,nelv) wt, integer n)
Definition at line 1261 of file hsmg.f.
hsmg_schwarz_wt3d()
subroutine hsmg_schwarz_wt3d (real, dimension(n,n,n,nelv) e, real, dimension(n,n,4,3,nelv) wt, integer n)
Definition at line 1285 of file hsmg.f.
hsmg_setup()
subroutine hsmg_setup
Definition at line 22 of file hsmg.f.
References hsmg_index_0(), hsmg_setup_dssum(), hsmg_setup_fdm(), hsmg_setup_intp(), hsmg_setup_mg_nx(), hsmg_setup_schwarz_wt(), hsmg_setup_semhat(), hsmg_setup_solve(), and hsmg_setup_wtmask().
hsmg_setup_dssum()
subroutine hsmg_setup_dssum
Definition at line 122 of file hsmg.f.
References get_vert(), and setupds().
hsmg_setup_fast()
subroutine hsmg_setup_fast (real, dimension(nl*nl,2,ldim,nelv) s, real, dimension(nl**ldim,nelv) d, nl, real, dimension(1) ah, real, dimension(1) bh, n)
Definition at line 701 of file hsmg.f.
References exitti(), get_fast_bc(), hsmg_setup_fast1d(), iglmax(), and vlmax().
hsmg_setup_fast1d()
subroutine hsmg_setup_fast1d (real, dimension(nl,nl,2) s, real, dimension(nl) lam, integer nl, integer lbc, integer rbc, real ll, real lm, real lr, real, dimension(0:n,0:n) ah, real, dimension(0:n) bh, integer n, ie)
Definition at line 783 of file hsmg.f.
References generalev(), hsmg_setup_fast1d_a(), hsmg_setup_fast1d_b(), row_zero(), and transpose().
hsmg_setup_fast1d_a()
subroutine hsmg_setup_fast1d_a (real, dimension(0:n+2,0:n+2) a, integer lbc, integer rbc, real ll, real lm, real lr, real, dimension(0:n,0:n) ah, integer n)
Definition at line 806 of file hsmg.f.
References rzero().
hsmg_setup_fast1d_b()
subroutine hsmg_setup_fast1d_b (real, dimension(0:n+2,0:n+2) b, integer lbc, integer rbc, real ll, real lm, real lr, real, dimension(0:n) bh, integer n)
Definition at line 848 of file hsmg.f.
References rzero().
hsmg_setup_fdm()
subroutine hsmg_setup_fdm
Definition at line 667 of file hsmg.f.
References exitt(), and hsmg_setup_fast().
hsmg_setup_intp()
subroutine hsmg_setup_intp
Definition at line 83 of file hsmg.f.
References hsmg_setup_intpm(), and transpose().
hsmg_setup_intpm()
subroutine hsmg_setup_intpm (real, dimension(nf,nc) jh, real, dimension(1) zf, real, dimension(1) zc, integer nf, integer nc)
Definition at line 108 of file hsmg.f.
References fd_weights_full().
hsmg_setup_mask()
subroutine hsmg_setup_mask (real, dimension(nx,nz,2,ldim,nelv) wt, integer nx, integer ny, integer nz, integer l, real, dimension(nx,ny,nz,nelv) w)
Definition at line 1069 of file hsmg.f.
References exitti(), get_fast_bc(), hsmg_dsprod(), iglmax(), and rone().
hsmg_setup_mg_nx()
subroutine hsmg_setup_mg_nx
Definition at line 1604 of file hsmg.f.
hsmg_setup_rstr_wt()
subroutine hsmg_setup_rstr_wt (real, dimension(nx,nz,2,ldim,nelv) wt, integer nx, integer ny, integer nz, integer l, real, dimension(nx,ny,nz,nelv) w)
Definition at line 987 of file hsmg.f.
References hsmg_dssum(), and rzero().
hsmg_setup_schwarz_wt()
subroutine hsmg_setup_schwarz_wt (logical ifsqrt)
Definition at line 1187 of file hsmg.f.
References exitt(), and h1mg_setup_schwarz_wt_1().
hsmg_setup_semhat()
subroutine hsmg_setup_semhat
Definition at line 50 of file hsmg.f.
References copy(), semhat(), and transpose().
hsmg_setup_solve()
subroutine hsmg_setup_solve
Definition at line 1356 of file hsmg.f.
References exitt().
hsmg_setup_wtmask()
subroutine hsmg_setup_wtmask
Definition at line 181 of file hsmg.f.
References exitt(), hsmg_setup_mask(), and hsmg_setup_rstr_wt().
hsmg_solve()
subroutine hsmg_solve (real, dimension(1) e, real, dimension(1) r)
Definition at line 1376 of file hsmg.f.
References avg1(), avg2(), cdabdtp(), cmult(), copy(), dnekclock(), glsc2(), gop(), hsmg_coarse_solve(), hsmg_do_wt(), hsmg_intp(), hsmg_rstr(), hsmg_rstr_no_dssum(), hsmg_schwarz(), hsmg_schwarz_wt(), local_solves_fdm(), ortho(), and vlsc2().
hsmg_tnsr()
subroutine hsmg_tnsr (real, dimension(1) v, integer nv, real, dimension(1) u, integer nu, real, dimension(1) A, real, dimension(1) At)
Definition at line 242 of file hsmg.f.
References hsmg_tnsr2d(), and hsmg_tnsr3d().
hsmg_tnsr1()
subroutine hsmg_tnsr1 (real, dimension(1) v, integer nv, integer nu, real, dimension(1) A, real, dimension(1) At)
Definition at line 2134 of file hsmg.f.
References hsmg_tnsr1_2d(), and hsmg_tnsr1_3d().
hsmg_tnsr1_2d()
subroutine hsmg_tnsr1_2d (real, dimension(1) v, integer nv, integer nu, real, dimension(1) A, real, dimension(1) Bt)
Definition at line 2151 of file hsmg.f.
References mxm().
hsmg_tnsr1_3d()
subroutine hsmg_tnsr1_3d (real, dimension(1) v, integer nv, integer nu, real, dimension(1) A, real, dimension(1) Bt, real, dimension(1) Ct)
Definition at line 2182 of file hsmg.f.
References mxm().
hsmg_tnsr2d()
subroutine hsmg_tnsr2d (real, dimension(nv*nv,nelv) v, integer nv, real, dimension(nu*nu,nelv) u, integer nu, real, dimension(1) A, real, dimension(1) Bt)
Definition at line 258 of file hsmg.f.
References mxm().
hsmg_tnsr2d_el()
subroutine hsmg_tnsr2d_el (real, dimension(nv*nv) v, integer nv, real, dimension(nu*nu) u, integer nu, real, dimension(1) A, real, dimension(1) Bt)
Definition at line 294 of file hsmg.f.
References mxm().
hsmg_tnsr3d()
subroutine hsmg_tnsr3d (real, dimension(nv*nv*nv,nelv) v, integer nv, real, dimension(nu*nu*nu,nelv) u, integer nu, real, dimension(1) A, real, dimension(1) Bt, real, dimension(1) Ct)
Definition at line 274 of file hsmg.f.
References mxm().
hsmg_tnsr3d_el()
subroutine hsmg_tnsr3d_el (real, dimension(nv*nv*nv) v, integer nv, real, dimension(nu*nu*nu) u, integer nu, real, dimension(1) A, real, dimension(1) Bt, real, dimension(1) Ct)
Definition at line 309 of file hsmg.f.
References mxm().
mg_intp_fc_e()
subroutine mg_intp_fc_e (real, dimension(nxc,nyc,nzc) uc, real, dimension(nxf,nyf,nzf) uf, nxc, nyc, nzc, nxf, nyf, nzf, integer e, l, real, dimension(1) w)
Definition at line 2604 of file hsmg.f.
References mxm().
mg_intp_gfc_e()
subroutine mg_intp_gfc_e (real, dimension(ng,nxc,nyc,nzc) gc, real, dimension(ng,nxf,nyf,nzf) gf, ng, nxc, nyc, nzc, nxf, nyf, nzf, integer e, l, real, dimension(1) w)
Definition at line 2656 of file hsmg.f.
References mxm().
mg_mask_e()
subroutine mg_mask_e (real, dimension(1) w, integer, dimension(0:1) mask)
Definition at line 2059 of file hsmg.f.
mg_scale_mass()
subroutine mg_scale_mass (real, dimension(1) b, real, dimension(ng,1) g, real, dimension(1) wt, ng, nx, ny, nz, real, dimension(1) wk, logical ifinv)
Definition at line 2719 of file hsmg.f.
References copy(), exitti(), and invers2().
mg_set_gb()
subroutine mg_set_gb (integer p_g, integer p_b, l0)
Definition at line 2784 of file hsmg.f.
References copy(), gxfer_e(), mg_intp_fc_e(), mg_intp_gfc_e(), and mg_scale_mass().
mg_set_h1()
subroutine mg_set_h1 (integer p_h1, l0)
Definition at line 2510 of file hsmg.f.
References copy(), and hsmg_intp_fc().
mg_set_h2()
subroutine mg_set_h2 (integer p_h2, l0)
Definition at line 2550 of file hsmg.f.
References copy(), and hsmg_intp_fc().
mg_set_msk()
subroutine mg_set_msk (integer p_msk, l0)
Definition at line 2396 of file hsmg.f.
References h1mg_setup_mask().
outflda()
subroutine outflda (real, dimension(1) x, n, character*10 txt10, ichk)
Definition at line 1796 of file hsmg.f.
References glmax(), glmin(), and glsum().
outfldan()
subroutine outfldan (real, dimension(1) x, n, character*10 txt10, ichk)
Definition at line 1825 of file hsmg.f.
References glmax(), glmin(), and glsum().
outfldn()
subroutine outfldn (real, dimension(n,n,1,lelt) x, n, character*10 txt10, ichk)
Definition at line 1679 of file hsmg.f.
References glmax(), and glmin().
outfldn0()
subroutine outfldn0 (real, dimension(n,n,1,lelt) x, n, character*10 txt10, ichk)
Definition at line 1738 of file hsmg.f.
References glmax(), and glmin().
outgmat()
subroutine outgmat (real, dimension(ng,nx,ny) a, ng, nx, ny, character*6 name6, k, integer e)
Definition at line 2904 of file hsmg.f.
References outmatz().
outmatz()
subroutine outmatz (real, dimension(m,n) a, m, n, character*6 name6, ie)
Definition at line 2928 of file hsmg.f.