KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/interp.f File Reference
interp.f File Reference
Functions/Subroutines
subroutine interp_setup (ih, tolin, nmsh, nelm)
subroutine interp_nfld (out, fld, nfld, xp, yp, zp, n, iwk, rwk, nmax, iflp, ih)
subroutine interp_free (ih)
subroutine intp_setup (tolin)
subroutine intp_do (fldout, fldin, nfld, xp, yp, zp, n, iwk, rwk, nmax, iflp)
subroutine intp_free ()
Function/Subroutine Documentation
interp_free()
subroutine interp_free (ih)
Definition at line 196 of file interp.f.
interp_nfld()
subroutine interp_nfld (real, dimension(*) out, real, dimension(*) fld, nfld, real, dimension(*) xp, real, dimension(*) yp, real, dimension(*) zp, n, integer, dimension(nmax,*) iwk, real, dimension(nmax,*) rwk, nmax, logical iflp, ih)
Definition at line 86 of file interp.f.
References exitt(), exitti(), and iglsum().
interp_setup()
subroutine interp_setup (ih, tolin, nmsh, nelm)
Definition at line 4 of file interp.f.
References exitti(), and map_m_to_n().
intp_do()
subroutine intp_do (fldout, fldin, nfld, xp, yp, zp, n, iwk, rwk, nmax, iflp)
Definition at line 216 of file interp.f.
References exitti().
intp_free()
subroutine intp_free
Definition at line 223 of file interp.f.
References exitti().
intp_setup()
subroutine intp_setup (tolin)
Definition at line 209 of file interp.f.
References exitti().