KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/intp_usr.f File Reference
intp_usr.f File Reference
Functions/Subroutines
subroutine intp_setup (tolin)
subroutine intp_do (fldout, fldin, nfld, xp, yp, zp, n, iwk, rwk, nmax, iflp)
subroutine intp_free ()
Function/Subroutine Documentation
intp_do()
subroutine intp_do (fldout, fldin, nfld, xp, yp, zp, n, iwk, rwk, nmax, iflp)
Definition at line 8 of file intp_usr.f.
References exitti().
intp_free()
subroutine intp_free
Definition at line 15 of file intp_usr.f.
References exitti().
intp_setup()
subroutine intp_setup (tolin)
Definition at line 1 of file intp_usr.f.
References exitti().