KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/experimental/lpm_solve.f File Reference
lpm_solve.f File Reference
Functions/Subroutines
subroutine lpm_init (rparam, yp, nyp, pp, npp, npart, time_)
subroutine lpm_rparam_set (rparam)
subroutine lpm_init_filter
subroutine lpm_tag_set
subroutine lpm_tag_init
subroutine lpm_solve (time_)
subroutine lpm_rk3_driver (time_, dt_, y0, y, ydot, n)
subroutine lpm_interpolate_setup
subroutine lpm_interpolate_fld (jp, fld)
subroutine lpm_project
subroutine lpm_solve_project
subroutine lpm_rk3_coeff (tcoef, rdt)
subroutine lpm_qtl_pvol (divin, phipin)
subroutine lpm_move_outlier
Function/Subroutine Documentation
lpm_init()
subroutine lpm_init (real, dimension(*) rparam, real, dimension(*) yp, nyp, real, dimension(*) pp, npp, npart, time_)
Definition at line 2 of file lpm_solve.f.
References copy(), domain_size(), exitti(), lpm_comm_setup(), lpm_init_filter(), lpm_interpolate_setup(), lpm_project(), lpm_rparam_set(), lpm_tag_init(), lpm_tag_set(), and nekgsync().
lpm_init_filter()
subroutine lpm_init_filter
Definition at line 90 of file lpm_solve.f.
References exitt(), glmax(), and glmin().
lpm_interpolate_fld()
subroutine lpm_interpolate_fld (jp, real, dimension(*) fld)
Definition at line 296 of file lpm_solve.f.
lpm_interpolate_setup()
subroutine lpm_interpolate_setup
Definition at line 283 of file lpm_solve.f.
References lpm_comm_bin_setup(), lpm_comm_crystal(), lpm_comm_findpts(), and lpm_move_outlier().
lpm_move_outlier()
subroutine lpm_move_outlier
Definition at line 677 of file lpm_solve.f.
References copy(), and icopy().
lpm_project()
subroutine lpm_project
Definition at line 333 of file lpm_solve.f.
References lpm_comm_ghost_create(), lpm_comm_ghost_send(), and lpm_solve_project().
lpm_qtl_pvol()
subroutine lpm_qtl_pvol (real, dimension(lx2,ly2,lz2,lelv) divin, real, dimension(lx1,ly1,lz1,lelt) phipin)
Definition at line 618 of file lpm_solve.f.
References add2(), chsign(), cmult(), copy(), invcol2(), map12(), opgrad(), rone(), rzero(), sub2(), sub3(), and vdot3().
lpm_rk3_coeff()
subroutine lpm_rk3_coeff (real, dimension(*) tcoef, real rdt)
Definition at line 598 of file lpm_solve.f.
lpm_rk3_driver()
subroutine lpm_rk3_driver (real time_, dt_, real, dimension(*) y0, real, dimension(*) y, real, dimension(*) ydot, n)
Definition at line 257 of file lpm_solve.f.
References lpm_rk3_coeff().
lpm_rparam_set()
subroutine lpm_rparam_set (real, dimension(*) rparam)
Definition at line 64 of file lpm_solve.f.
lpm_solve()
subroutine lpm_solve (real time_)
Definition at line 226 of file lpm_solve.f.
References copy(), dnekclock(), exitti(), and lpm_rk3_driver().
lpm_solve_project()
subroutine lpm_solve_project
Definition at line 346 of file lpm_solve.f.
References icopy(), and rzero().
lpm_tag_init()
subroutine lpm_tag_init
Definition at line 210 of file lpm_solve.f.
lpm_tag_set()
subroutine lpm_tag_set
Definition at line 196 of file lpm_solve.f.