KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/experimental/lpm_io.f File Reference
lpm_io.f File Reference
Functions/Subroutines
subroutine lpm_io_read (filein1, npart)
subroutine lpm_io_write (filein1, iobig)
subroutine lpm_io_vtu_data (vtu, dataname, ncomp, idist)
subroutine lpm_io_read_restart (filename)
Function/Subroutine Documentation
lpm_io_read()
subroutine lpm_io_read (character (len = *) filein1, npart)
Definition at line 2 of file lpm_io.f.
References bcast(), byte_close_mpi(), byte_open_mpi(), byte_read_mpi(), byte_set_view(), iadd(), and iglsum().
lpm_io_read_restart()
subroutine lpm_io_read_restart (character*12 filename)
Definition at line 522 of file lpm_io.f.
References bcast(), byte_close_mpi(), byte_open_mpi(), byte_read_mpi(), byte_set_view(), lpm_comm_crystal(), and lpm_comm_findpts().
lpm_io_vtu_data()
subroutine lpm_io_vtu_data (integer vtu, character (len = *) dataname, integer ncomp, integer*4 idist)
Definition at line 501 of file lpm_io.f.
lpm_io_write()
subroutine lpm_io_write (character, dimension(*) filein1, iobig)
Definition at line 174 of file lpm_io.f.
References bcast(), byte_close_mpi(), byte_open_mpi(), byte_set_view(), byte_write_mpi(), dnekclock_sync(), iadd(), iglsum(), and lpm_io_vtu_data().