KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/experimental/lpm_comm.f File Reference
lpm_comm.f File Reference
Functions/Subroutines
subroutine lpm_comm_setup
subroutine lpm_comm_findpts
integer function nid_glcount (a, is, n)
subroutine lpm_comm_crystal
subroutine lpm_comm_bin_setup
subroutine lpm_comm_ghost_create
subroutine lpm_comm_check_periodic_gp (rxnew, rxdrng, iadd)
subroutine lpm_comm_ghost_send
Function/Subroutine Documentation
lpm_comm_bin_setup()
subroutine lpm_comm_bin_setup
Definition at line 187 of file lpm_comm.f.
References copy(), exitt(), glmax(), glmin(), icopy(), vlmax(), and vlmin().
lpm_comm_check_periodic_gp()
subroutine lpm_comm_check_periodic_gp (real, dimension(3) rxnew, real, dimension(3) rxdrng, integer, dimension(3) iadd)
Definition at line 901 of file lpm_comm.f.
lpm_comm_crystal()
subroutine lpm_comm_crystal
Definition at line 135 of file lpm_comm.f.
References copy().
lpm_comm_findpts()
subroutine lpm_comm_findpts
Definition at line 18 of file lpm_comm.f.
References exitti(), iglmax(), iglsum(), and nid_glcount().
lpm_comm_ghost_create()
subroutine lpm_comm_ghost_create
Definition at line 521 of file lpm_comm.f.
References lpm_comm_check_periodic_gp().
lpm_comm_ghost_send()
subroutine lpm_comm_ghost_send
Definition at line 982 of file lpm_comm.f.
lpm_comm_setup()
subroutine lpm_comm_setup
Definition at line 2 of file lpm_comm.f.
References interp_setup().
nid_glcount()
integer function nid_glcount (integer, dimension(*) a, is, n)
Definition at line 80 of file lpm_comm.f.