KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/makeq_aux.f File Reference
makeq_aux.f File Reference
Functions/Subroutines
subroutine makeq_aux
Function/Subroutine Documentation
makeq_aux()
subroutine makeq_aux
Definition at line 1 of file makeq_aux.f.
References add2s2(), make_hpf(), and makeuq().