KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/math.f File Reference
math.f File Reference
Functions/Subroutines
subroutine icopy48 (a, b, n)
subroutine icopy84 (a, b, n)
subroutine blank (A, N)
subroutine vsq (A, N)
subroutine vsqrt (A, N)
subroutine invers2 (a, b, n)
subroutine invcol1 (a, n)
subroutine invcol2 (a, b, n)
subroutine invcol3 (a, b, c, n)
subroutine col4 (a, b, c, d, n)
subroutine xaddcol3 (a, b, c, n)
subroutine addcol4 (a, b, c, d, n)
subroutine ascol5 (a, b, c, d, e, n)
subroutine sub2 (a, b, n)
subroutine sub3 (a, b, c, n)
subroutine subcol3 (a, b, c, n)
subroutine subcol4 (a, b, c, d, n)
subroutine rzero (a, n)
subroutine izero (a, n)
subroutine ione (a, n)
subroutine rone (a, n)
subroutine ltrue (a, n)
subroutine cfill (a, b, n)
subroutine ifill (ia, ib, n)
subroutine copy (a, b, n)
subroutine copyi4 (a, b, n)
subroutine chcopy (a, b, n)
subroutine icopy (a, b, n)
subroutine i8copy (a, b, n)
subroutine chsign (a, n)
subroutine cmult (a, const, n)
subroutine cadd (a, const, n)
subroutine iadd (i1, iscal, n)
subroutine cadd2 (a, b, const, n)
real function vlmin (vec, n)
integer function ivlmin (vec, n)
integer function ivlmax (vec, n)
real function vlmax (vec, n)
real function vlamax (vec, n)
real function vlsum (vec, n)
subroutine vcross (u1, u2, u3, v1, v2, v3, w1, w2, w3, n)
subroutine vdot2 (dot, u1, u2, v1, v2, n)
subroutine vdot3 (dot, u1, u2, u3, v1, v2, v3, n)
subroutine addtnsr (s, h1, h2, h3, nx, ny, nz)
function ltrunc (string, l)
function mod1 (i, n)
integer function log2 (k)
subroutine iflip (i1, n)
subroutine iswap (b, ind, n, temp)
subroutine col2 (a, b, n)
subroutine col2c (a, b, c, n)
subroutine col3 (a, b, c, n)
subroutine add2 (a, b, n)
subroutine add3 (a, b, c, n)
subroutine addcol3 (a, b, c, n)
subroutine add2s1 (a, b, c1, n)
subroutine add2s2 (a, b, c1, n)
subroutine add3s2 (a, b, c, c1, c2, n)
subroutine add4 (a, b, c, d, n)
real function vlsc2 (x, y, n)
real function vlsc21 (x, y, n)
function glsc3 (a, b, mult, n)
function glsc2 (x, y, n)
function glsc23 (x, y, z, n)
real function gl2norm (a, n)
real function gl2norm2 (a, n)
function glsum (x, n)
real function glamax (a, n)
real function glamin (a, n)
function iglmin (a, n)
function iglmax (a, n)
function iglsum (a, n)
subroutine i8zero (a, n)
integer *8 function i8glsum (a, n)
function glmax (a, n)
function glmin (a, n)
subroutine gllog (la, lb)
function fmdian (a, n, ifok)
subroutine dcadd (a, const, n)
subroutine dsub2 (a, b, n)
subroutine dadd2 (a, b, n)
subroutine chswapr (b, L, ind, n, temp)
subroutine drcopy (r, d, N)
subroutine rrcopy (r, d, N)
subroutine sorts (xout, xin, work, n)
function ivlsum (a, n)
subroutine icadd (a, c, n)
subroutine isort (a, ind, n)
subroutine sort (a, ind, n)
subroutine iswap_ip (x, p, n)
subroutine iswapt_ip (x, p, n)
subroutine swap_ip (x, p, n)
subroutine swapt_ip (x, p, n)
subroutine glvadd (x, w, n)
subroutine add3s12 (x, y, z, c1, c2, n)
integer *8 function i8glmax (a, n)
subroutine admcol3 (a, b, c, d, n)
subroutine add2col2 (a, b, c, n)
subroutine add2sxy (x, a, y, b, n)
subroutine col2s2 (x, y, s, n)
subroutine transpose (a, lda, b, ldb)
subroutine transpose1 (a, n)
real function difmax (a, b, n)
function glmin_ms (a, n)
function glamin_ms (a, n)
function glmax_ms (a, n)
function glamax_ms (a, n)
function glsum_ms (a, n)
function iglsum_ms (a, n)
function glsc3_ms (a, b, c, n)
function glsc2_ms (a, b, n)
function iglmax_ms (a, n)
function iglmin_ms (a, n)
Function/Subroutine Documentation
add2()
subroutine add2 (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 621 of file math.f.
References dnekclock().
add2col2()
subroutine add2col2 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 1564 of file math.f.
add2s1()
subroutine add2s1 (real, dimension(1) a, real, dimension(1) b, c1, n)
Definition at line 677 of file math.f.
add2s2()
subroutine add2s2 (real, dimension(1) a, real, dimension(1) b, c1, n)
Definition at line 689 of file math.f.
References dnekclock().
add2sxy()
subroutine add2sxy (real, dimension(1) x, a, real, dimension(1) y, b, n)
Definition at line 1573 of file math.f.
add3()
subroutine add3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 643 of file math.f.
add3s12()
subroutine add3s12 (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, real c1, real c2, n)
Definition at line 1533 of file math.f.
add3s2()
subroutine add3s2 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, c1, c2, n)
Definition at line 715 of file math.f.
add4()
subroutine add4 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, real, dimension(1) d, n)
Definition at line 727 of file math.f.
addcol3()
subroutine addcol3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 653 of file math.f.
References dnekclock().
addcol4()
subroutine addcol4 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, real, dimension(1) d, n)
Definition at line 141 of file math.f.
addtnsr()
subroutine addtnsr (dimension(nx,ny,nz) s, dimension(1) h1, dimension(1) h2, dimension(1) h3, nx, ny, nz)
Definition at line 476 of file math.f.
admcol3()
subroutine admcol3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, real d, n)
Definition at line 1555 of file math.f.
ascol5()
subroutine ascol5 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, real, dimension(1) d, real, dimension(1) e, n)
Definition at line 152 of file math.f.
blank()
subroutine blank (character*1, dimension(1) A, N)
Definition at line 18 of file math.f.
cadd()
subroutine cadd (real, dimension(1) a, const, n)
Definition at line 325 of file math.f.
cadd2()
subroutine cadd2 (real, dimension(1) a, real, dimension(1) b, const, n)
Definition at line 345 of file math.f.
cfill()
subroutine cfill (dimension(1) a, b, n)
Definition at line 243 of file math.f.
chcopy()
subroutine chcopy (character*1, dimension(1) a, character*1, dimension(1) b, n)
Definition at line 280 of file math.f.
chsign()
subroutine chsign (real, dimension(1) a, n)
Definition at line 304 of file math.f.
chswapr()
subroutine chswapr (character*6, dimension(1) b, L, integer, dimension(1) ind, n, character*6, dimension(1) temp)
Definition at line 1209 of file math.f.
cmult()
subroutine cmult (real, dimension(1) a, const, n)
Definition at line 314 of file math.f.
col2()
subroutine col2 (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 563 of file math.f.
References dnekclock().
col2c()
subroutine col2c (real, dimension(1) a, real, dimension(1) b, real c, n)
Definition at line 587 of file math.f.
col2s2()
subroutine col2s2 (real, dimension(n) x, real, dimension(n) y, s, n)
Definition at line 1583 of file math.f.
col3()
subroutine col3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 597 of file math.f.
References dnekclock().
col4()
subroutine col4 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, real, dimension(1) d, n)
Definition at line 119 of file math.f.
copy()
subroutine copy (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 259 of file math.f.
copyi4()
subroutine copyi4 (integer, dimension(1) a, real, dimension(1) b, n)
Definition at line 269 of file math.f.
dadd2()
subroutine dadd2 (real*8, dimension(1) a, real*8, dimension(1) b, n)
Definition at line 1200 of file math.f.
dcadd()
subroutine dcadd (real*8, dimension(1) a, real*8 const, n)
Definition at line 1181 of file math.f.
difmax()
real function difmax (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 1617 of file math.f.
References glamax().
drcopy()
subroutine drcopy (dimension(1) r, real*8, dimension(1) d, N)
Definition at line 1225 of file math.f.
dsub2()
subroutine dsub2 (real*8, dimension(1) a, real*8, dimension(1) b, n)
Definition at line 1190 of file math.f.
fmdian()
function fmdian (dimension(1) a, n, logical ifok)
Definition at line 1003 of file math.f.
References exitt(), glmax(), glmin(), gop(), and rzero().
gl2norm()
real function gl2norm (real, dimension(1) a, n)
Definition at line 828 of file math.f.
References col2(), col3(), and glsum().
gl2norm2()
real function gl2norm2 (real, dimension(n) a, n)
Definition at line 844 of file math.f.
References col2(), col3(), and glsum().
glamax()
real function glamax (real, dimension(1) a, n)
Definition at line 873 of file math.f.
References gop().
glamax_ms()
function glamax_ms (real, dimension(1) a, n)
Definition at line 1668 of file math.f.
References glamax(), and setnekcomm().
glamin()
real function glamin (real, dimension(1) a, n)
Definition at line 886 of file math.f.
References gop().
glamin_ms()
function glamin_ms (real, dimension(1) a, n)
Definition at line 1644 of file math.f.
References glamin(), and setnekcomm().
gllog()
subroutine gllog (logical la, logical lb)
Definition at line 985 of file math.f.
References gop().
glmax()
function glmax (real, dimension(1) a, n)
Definition at line 959 of file math.f.
References gop().
glmax_ms()
function glmax_ms (real, dimension(1) a, n)
Definition at line 1656 of file math.f.
References glmax(), and setnekcomm().
glmin()
function glmin (real, dimension(1) a, n)
Definition at line 972 of file math.f.
References gop().
glmin_ms()
function glmin_ms (real, dimension(1) a, n)
Definition at line 1632 of file math.f.
References glmin(), and setnekcomm().
glsc2()
function glsc2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 793 of file math.f.
References gop().
glsc23()
function glsc23 (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, n)
Definition at line 811 of file math.f.
References gop().
glsc2_ms()
function glsc2_ms (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 1716 of file math.f.
References glsc2(), and setnekcomm().
glsc3()
function glsc3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) mult, n)
Definition at line 775 of file math.f.
References gop().
glsc3_ms()
function glsc3_ms (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 1704 of file math.f.
References glsc3(), and setnekcomm().
glsum()
function glsum (dimension(1) x, n)
Definition at line 860 of file math.f.
References gop().
glsum_ms()
function glsum_ms (real, dimension(1) a, n)
Definition at line 1680 of file math.f.
References glsum(), and setnekcomm().
glvadd()
subroutine glvadd (real, dimension(1) x, real, dimension(1) w, n)
Definition at line 1527 of file math.f.
References gop().
i8copy()
subroutine i8copy (integer*8, dimension(1) a, integer*8, dimension(1) b, n)
Definition at line 296 of file math.f.
i8glmax()
integer*8 function i8glmax (integer*8, dimension(1) a, n)
Definition at line 1541 of file math.f.
References i8gop().
i8glsum()
integer*8 function i8glsum (integer*8, dimension(1) a, n)
Definition at line 946 of file math.f.
References i8gop().
i8zero()
subroutine i8zero (integer*8, dimension(1) a, n)
Definition at line 938 of file math.f.
iadd()
subroutine iadd (dimension(1) i1, iscal, n)
Definition at line 336 of file math.f.
icadd()
subroutine icadd (integer, dimension(1) a, integer c, n)
Definition at line 1266 of file math.f.
icopy()
subroutine icopy (integer, dimension(1) a, integer, dimension(1) b, n)
Definition at line 288 of file math.f.
icopy48()
subroutine icopy48 (integer*8, dimension(1) a, integer*4, dimension(1) b, n)
Definition at line 2 of file math.f.
icopy84()
subroutine icopy84 (integer*4, dimension(1) a, integer*8, dimension(1) b, n)
Definition at line 10 of file math.f.
ifill()
subroutine ifill (dimension(1) ia, ib, n)
Definition at line 251 of file math.f.
iflip()
subroutine iflip (dimension(1) i1, n)
Definition at line 535 of file math.f.
iglmax()
function iglmax (integer, dimension(1) a, n)
Definition at line 912 of file math.f.
References igop().
iglmax_ms()
function iglmax_ms (integer, dimension(1) a, n)
Definition at line 1728 of file math.f.
References iglmax(), and setnekcomm().
iglmin()
function iglmin (integer, dimension(1) a, n)
Definition at line 899 of file math.f.
References igop().
iglmin_ms()
function iglmin_ms (integer, dimension(1) a, n)
Definition at line 1740 of file math.f.
References iglmin(), and setnekcomm().
iglsum()
function iglsum (integer, dimension(1) a, n)
Definition at line 925 of file math.f.
References igop().
iglsum_ms()
function iglsum_ms (integer, dimension(1) a, integer n)
Definition at line 1692 of file math.f.
References iglsum(), and setnekcomm().
invcol1()
subroutine invcol1 (real, dimension(1) a, n)
Definition at line 61 of file math.f.
invcol2()
subroutine invcol2 (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 72 of file math.f.
References dnekclock().
invcol3()
subroutine invcol3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 97 of file math.f.
References dnekclock().
invers2()
subroutine invers2 (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 50 of file math.f.
ione()
subroutine ione (integer, dimension(1) a, n)
Definition at line 222 of file math.f.
isort()
subroutine isort (integer, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 1272 of file math.f.
iswap()
subroutine iswap (integer, dimension(1) b, integer, dimension(1) ind, n, integer, dimension(1) temp)
Definition at line 548 of file math.f.
iswap_ip()
subroutine iswap_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 1377 of file math.f.
References exitt().
iswapt_ip()
subroutine iswapt_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 1413 of file math.f.
References exitt().
ivlmax()
integer function ivlmax (integer, dimension(1) vec, n)
Definition at line 381 of file math.f.
ivlmin()
integer function ivlmin (integer, dimension(1) vec, n)
Definition at line 367 of file math.f.
ivlsum()
function ivlsum (integer, dimension(1) a, n)
Definition at line 1251 of file math.f.
izero()
subroutine izero (integer, dimension(1) a, n)
Definition at line 214 of file math.f.
log2()
integer function log2 (k)
Definition at line 526 of file math.f.
ltrue()
subroutine ltrue (logical, dimension(1) a, n)
Definition at line 236 of file math.f.
ltrunc()
function ltrunc (character*1, dimension(l) string, l)
Definition at line 493 of file math.f.
mod1()
function mod1 (i, n)
Definition at line 508 of file math.f.
rone()
subroutine rone (dimension(1) a, n)
Definition at line 229 of file math.f.
rrcopy()
subroutine rrcopy (real*4, dimension(1) r, real*4, dimension(1) d, N)
Definition at line 1234 of file math.f.
rzero()
subroutine rzero (dimension(1) a, n)
Definition at line 207 of file math.f.
sort()
subroutine sort (real, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 1324 of file math.f.
sorts()
subroutine sorts (real, dimension(1) xout, real, dimension(1) xin, real, dimension(1) work, n)
Definition at line 1243 of file math.f.
References copy(), and sort().
sub2()
subroutine sub2 (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 163 of file math.f.
sub3()
subroutine sub3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 174 of file math.f.
subcol3()
subroutine subcol3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 185 of file math.f.
subcol4()
subroutine subcol4 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, real, dimension(1) d, n)
Definition at line 196 of file math.f.
swap_ip()
subroutine swap_ip (real, dimension(1) x, integer, dimension(1) p, n)
Definition at line 1452 of file math.f.
References exitt().
swapt_ip()
subroutine swapt_ip (real, dimension(1) x, integer, dimension(1) p, n)
Definition at line 1488 of file math.f.
References exitt().
transpose()
subroutine transpose (real, dimension(lda,1) a, lda, real, dimension(ldb,1) b, ldb)
Definition at line 1593 of file math.f.
transpose1()
subroutine transpose1 (real, dimension(n,n) a, n)
Definition at line 1604 of file math.f.
vcross()
subroutine vcross (dimension(1) u1, dimension(1) u2, dimension(1) u3, dimension(1) v1, dimension(1) v2, dimension(1) v3, dimension(1) w1, dimension(1) w2, dimension(1) w3, n)
Definition at line 429 of file math.f.
vdot2()
subroutine vdot2 (dimension(1) dot, dimension(1) u1, dimension(1) u2, dimension(1) v1, dimension(1) v2, n)
Definition at line 446 of file math.f.
References dot().
vdot3()
subroutine vdot3 (dimension(1) dot, dimension(1) u1, dimension(1) u2, dimension(1) u3, dimension(1) v1, dimension(1) v2, dimension(1) v3, n)
Definition at line 461 of file math.f.
References dot().
vlamax()
real function vlamax (real, dimension(1) vec, n)
Definition at line 405 of file math.f.
vlmax()
real function vlmax (real, dimension(1) vec, n)
Definition at line 395 of file math.f.
vlmin()
real function vlmin (real, dimension(1) vec, n)
Definition at line 356 of file math.f.
vlsc2()
real function vlsc2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 738 of file math.f.
vlsc21()
real function vlsc21 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 752 of file math.f.
vlsum()
real function vlsum (real, dimension(1) vec, n)
Definition at line 416 of file math.f.
vsq()
subroutine vsq (dimension(1) A, N)
Definition at line 30 of file math.f.
vsqrt()
subroutine vsqrt (dimension(1) A, N)
Definition at line 40 of file math.f.
xaddcol3()
subroutine xaddcol3 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 130 of file math.f.