KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/multimesh.f File Reference
multimesh.f File Reference
Functions/Subroutines
subroutine setup_neknek_wts
subroutine neknek_setup
subroutine set_intflag
subroutine bcopy
subroutine chk_outflow
subroutine neknekmv ()
subroutine setup_int_neknek (dxf, dyf, dzf)
subroutine exchange_points (dxf, dyf, dzf)
subroutine neknek_exchange
subroutine field_eval (fieldout, fieldstride, fieldin)
subroutine nekneksanchk
subroutine neknek_xfer_fld (u, ui)
subroutine fix_surface_flux
subroutine surface_flux_area (dq, aq, qx, qy, qz, e, f, w)
subroutine rescale_x_ms (x, x0, x1)
subroutine vol_flow_ms
subroutine compute_vol_soln_ms (vxc, vyc, vzc, prc)
subroutine plan3_vol_ms (vxc, vyc, vzc, prc)
subroutine plan4_vol_ms (vxc, vyc, vzc, prc)
Function/Subroutine Documentation
bcopy()
subroutine bcopy
Definition at line 127 of file multimesh.f.
References copy().
chk_outflow()
subroutine chk_outflow
Definition at line 174 of file multimesh.f.
References facind().
compute_vol_soln_ms()
subroutine compute_vol_soln_ms (real, dimension(lx1,ly1,lz1,lelv) vxc, real, dimension(lx1,ly1,lz1,lelv) vyc, real, dimension(lx1,ly1,lz1,lelv) vzc, real, dimension(lx2,ly2,lz2,lelv) prc)
Definition at line 770 of file multimesh.f.
References glmax_ms(), glmin_ms(), glsc2_ms(), plan3_vol_ms(), and plan4_vol_ms().
exchange_points()
subroutine exchange_points (dxf, dyf, dzf)
Definition at line 283 of file multimesh.f.
References cadd(), exitt(), facind(), iglmax_ms(), iglsum(), izero(), nekasgn(), and neknekgsync().
field_eval()
subroutine field_eval (real, dimension(1) fieldout, integer fieldstride, real, dimension(1) fieldin)
Definition at line 474 of file multimesh.f.
fix_surface_flux()
subroutine fix_surface_flux
Definition at line 529 of file multimesh.f.
References facind(), glsum(), iglmax(), and surface_flux_area().
neknek_exchange()
subroutine neknek_exchange
Definition at line 417 of file multimesh.f.
References dnekclock(), dnekclock_sync(), field_eval(), mappr(), nekgsync(), and neknekgsync().
neknek_setup()
subroutine neknek_setup
Definition at line 28 of file multimesh.f.
References exchange_points(), exitti(), fix_geom(), geom_reset(), iglmax_ms(), iglmin_ms(), neknekmv(), set_intflag(), setup_int_neknek(), and setup_neknek_wts().
neknek_xfer_fld()
subroutine neknek_xfer_fld (real, dimension(1) u, real, dimension(1) ui)
Definition at line 508 of file multimesh.f.
References field_eval(), and neknekgsync().
neknekmv()
subroutine neknekmv
Definition at line 214 of file multimesh.f.
References iglmin_ms().
nekneksanchk()
subroutine nekneksanchk
Definition at line 493 of file multimesh.f.
References exitti().
plan3_vol_ms()
subroutine plan3_vol_ms (real, dimension(lx1,ly1,lz1,lelv) vxc, real, dimension(lx1,ly1,lz1,lelv) vyc, real, dimension(lx1,ly1,lz1,lelv) vzc, real, dimension(lx2,ly2,lz2,lelv) prc)
Definition at line 835 of file multimesh.f.
References chsign(), cmult(), cmult2(), copy(), esolver(), glamax_ms(), invers2(), neknek_xfer_fld(), neknekgsync(), opadd2(), opbinv(), opdiv(), opgradt(), ophinv(), ophx(), opzero(), ortho(), outpost(), rzero(), sethlm(), ssnormd(), sub2(), and sub3().
plan4_vol_ms()
subroutine plan4_vol_ms (real, dimension(lx1,ly1,lz1,lelv) vxc, real, dimension(lx1,ly1,lz1,lelv) vyc, real, dimension(lx1,ly1,lz1,lelv) vzc, real, dimension(lx2,ly2,lz2,lelv) prc)
Definition at line 975 of file multimesh.f.
References add2(), add2col2(), cdtp(), cmult(), col2(), copy(), ctolspl(), faccl2(), faccl3(), glamax_ms(), hmholtz(), invers2(), neknek_xfer_fld(), opadd2(), opchsgn(), opgrad(), ophinv(), ophx(), opzero(), ortho(), redo_split_vis(), rzero(), sethlm(), split_vis(), sub2(), and sub3().
rescale_x_ms()
subroutine rescale_x_ms (real, dimension(1) x, x0, x1)
Definition at line 630 of file multimesh.f.
References glmax(), glmax_ms(), glmin(), glmin_ms(), and scale().
set_intflag()
subroutine set_intflag
Definition at line 83 of file multimesh.f.
References izero(), and rzero().
setup_int_neknek()
subroutine setup_int_neknek (real dxf, real dyf, real dzf)
Definition at line 232 of file multimesh.f.
References cadd(), glmax_ms(), and glmin_ms().
setup_neknek_wts()
subroutine setup_neknek_wts
Definition at line 15 of file multimesh.f.
References col3(), and rone().
surface_flux_area()
subroutine surface_flux_area (dq, aq, real, dimension(l,1) qx, real, dimension(l,1) qy, real, dimension(l,1) qz, integer e, integer f, real, dimension(lx1,ly1,lz1) w)
Definition at line 598 of file multimesh.f.
References dsset(), faccl3(), and faddcl3().
vol_flow_ms()
subroutine vol_flow_ms
Definition at line 654 of file multimesh.f.
References add2s2(), compute_vol_soln_ms(), copy(), exitt(), glsc2_ms(), glsum_ms(), and scale().