KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier2.f File Reference
navier2.f File Reference
Functions/Subroutines
subroutine aspect_ratios (ar)
subroutine eig2 (AA, eign, eig1)
subroutine quadratic_h (x1, x2, a, b, c)
subroutine out_sem (iel)
subroutine gradm11 (ux, uy, uz, u, e)
Function/Subroutine Documentation
aspect_ratios()
subroutine aspect_ratios (real, dimension(1) ar)
Definition at line 2 of file navier2.f.
References cmult(), eig2(), rzero(), vlsc2(), and vlsum().
eig2()
subroutine eig2 (real, dimension(2,2) AA, eign, eig1)
Definition at line 79 of file navier2.f.
References quadratic_h().
gradm11()
subroutine gradm11 (real, dimension(lxyz) ux, real, dimension(lxyz) uy, real, dimension(lxyz) uz, real, dimension(lxyz,1) u, integer e)
Definition at line 175 of file navier2.f.
References local_grad2(), local_grad3(), and setaxdy().
out_sem()
subroutine out_sem (iel)
Definition at line 148 of file navier2.f.
quadratic_h()
subroutine quadratic_h (x1, x2, a, b, c)
Definition at line 98 of file navier2.f.