KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier0.f File Reference
navier0.f File Reference
Functions/Subroutines
subroutine esolver (RES, H1, H2, H2INV, INTYPE)
subroutine dmp_map (imap)
subroutine p_outvec_ir (ia, a, lda, name9)
Function/Subroutine Documentation
dmp_map()
subroutine dmp_map (integer, dimension(nelgt) imap)
Definition at line 46 of file navier0.f.
References p_outvec_ir().
esolver()
subroutine esolver (real, dimension (lx2,ly2,lz2,lelv) RES, real, dimension (lx1,ly1,lz1,lelv) H1, real, dimension (lx1,ly1,lz1,lelv) H2, real, dimension (lx1,ly1,lz1,lelv) H2INV, INTYPE)
Definition at line 1 of file navier0.f.
References dnekclock(), exitt(), ortho(), uzawa(), and uzawa_gmres().
p_outvec_ir()
subroutine p_outvec_ir (integer, dimension(1) ia, real, dimension(lda,1) a, lda, character*9 name9)
Definition at line 76 of file navier0.f.
References copy(), crecv2(), csend(), gllel(), gllnid(), icopy(), and nekgsync().