KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier7.f File Reference
navier7.f File Reference
Functions/Subroutines
subroutine out_acsr (acsr, ia, ja, n)
subroutine compress_acsr (acsr, ia, ja, n)
subroutine outbox (xmax, xmin, ymax, ymin, io)
subroutine imout (x, m, n, name)
subroutine out_abd (abd, lda, n, m)
subroutine rarr_out (x, name13)
subroutine iarr_out (x, name)
subroutine iar2_out (x, name)
subroutine scsr_permute (bcsr, ib, jb, acsr, ia, ja, n, icperm, inverse, nonzero, nzero)
subroutine scsr_to_spb (abd, lda, acsr, ia, ja, n)
subroutine scsr_to_spbm (abd, lda, acsr, ia, ja, n)
function mbw_csr (ia, ja, n)
subroutine out_spbmat (abd, n, lda, name)
subroutine swap (b, ind, n, temp)
subroutine ipermute (a, icperm, n, b)
subroutine out_csrmat (acsr, ia, ja, n, name9)
Function/Subroutine Documentation
compress_acsr()
subroutine compress_acsr (real, dimension(1) acsr, integer, dimension(1) ia, integer, dimension(1) ja, n)
Definition at line 38 of file navier7.f.
iar2_out()
subroutine iar2_out (integer, dimension(lx2,ly2,lz2,lelt) x, character*13 name)
Definition at line 240 of file navier7.f.
iarr_out()
subroutine iarr_out (integer, dimension(lx1,ly1,lz1,lelt) x, character*13 name)
Definition at line 194 of file navier7.f.
imout()
subroutine imout (integer, dimension(m,1) x, m, n, character*9 name)
Definition at line 104 of file navier7.f.
ipermute()
subroutine ipermute (integer, dimension(1) a, integer, dimension(1) icperm, n, integer, dimension(1) b)
Definition at line 519 of file navier7.f.
References icopy().
mbw_csr()
function mbw_csr (integer, dimension(1) ia, integer, dimension(1) ja, n)
Definition at line 457 of file navier7.f.
out_abd()
subroutine out_abd (real, dimension(lda,1) abd, lda, n, m)
Definition at line 116 of file navier7.f.
out_acsr()
subroutine out_acsr (real, dimension(1) acsr, integer, dimension(2) ia, integer, dimension(1) ja, n)
Definition at line 2 of file navier7.f.
out_csrmat()
subroutine out_csrmat (real, dimension(1) acsr, integer, dimension(1) ia, integer, dimension(1) ja, n, character*9 name9)
Definition at line 530 of file navier7.f.
References blank().
out_spbmat()
subroutine out_spbmat (real, dimension(lda,1) abd, n, lda, character*9 name)
Definition at line 476 of file navier7.f.
References blank().
outbox()
subroutine outbox (xmax, xmin, ymax, ymin, io)
Definition at line 80 of file navier7.f.
rarr_out()
subroutine rarr_out (real, dimension(lx1,ly1,lz1,lelt) x, character*13 name13)
Definition at line 148 of file navier7.f.
scsr_permute()
subroutine scsr_permute (real, dimension(1) bcsr, integer, dimension(1) ib, integer, dimension(1) jb, real, dimension(1) acsr, integer, dimension(1) ia, integer, dimension(1) ja, n, integer, dimension(n) icperm, integer, dimension(n) inverse, integer, dimension(2,0:1) nonzero, integer, dimension(n) nzero)
Definition at line 267 of file navier7.f.
References exitt(), icopy(), isort(), izero(), mbw_csr(), and swap().
scsr_to_spb()
subroutine scsr_to_spb (real, dimension(1) abd, lda, real, dimension(1) acsr, integer, dimension(1) ia, integer, dimension(1) ja, integer n)
Definition at line 423 of file navier7.f.
References mbw_csr(), and scsr_to_spbm().
scsr_to_spbm()
subroutine scsr_to_spbm (real, dimension(lda,1) abd, lda, real, dimension(1) acsr, integer, dimension(1) ia, integer, dimension(1) ja, integer n)
Definition at line 439 of file navier7.f.
References rzero().
swap()
subroutine swap (real, dimension(1) b, integer, dimension(1) ind, n, real, dimension(1) temp)
Definition at line 503 of file navier7.f.