KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/3rd_party/nek_in_situ.f File Reference
nek_in_situ.f File Reference
Functions/Subroutines
subroutine in_situ_init ()
subroutine in_situ_check ()
subroutine in_situ_end ()
Function/Subroutine Documentation
in_situ_check()
subroutine in_situ_check
Definition at line 8 of file nek_in_situ.f.
References visit_check().
in_situ_end()
subroutine in_situ_end
Definition at line 14 of file nek_in_situ.f.
References visit_end().
in_situ_init()
subroutine in_situ_init
Definition at line 2 of file nek_in_situ.f.
References visit_init().