KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/plan4.f File Reference
plan4.f File Reference
Functions/Subroutines
subroutine plan4 (igeom)
subroutine crespsp (respr)
subroutine cresvsp (resv1, resv2, resv3, h1, h2)
subroutine cresvsp_weak (resv1, resv2, resv3, h1, h2)
subroutine op_curl (w1, w2, w3, u1, u2, u3, ifavg, work1, work2)
subroutine opadd2cm (a1, a2, a3, b1, b2, b3, c)
subroutine split_vis
subroutine redo_split_vis
subroutine col_mu_sij (w1, w2, w3, ta1, ta2, ta3, sij, nij)
subroutine sumab (v, vv, vvlag, ntot, ab_, nab_)
subroutine userqtl_scig
subroutine qthermal
subroutine printdiverr
subroutine bcdirpr (S)
Function/Subroutine Documentation
bcdirpr()
subroutine bcdirpr (dimension(lx1,ly1,lz1,lelt) S)
Definition at line 708 of file plan4.f.
References add2(), col2(), dnekclock(), dsop(), faceis(), and rzero().
col_mu_sij()
subroutine col_mu_sij (real, dimension (lr,1) w1, real, dimension (lr,1) w2, real, dimension (lr,1) w3, real, dimension(lr,1) ta1, real, dimension(lr,1) ta2, real, dimension(lr,1) ta3, real, dimension(lr,nij,1) sij, nij)
Definition at line 487 of file plan4.f.
References rzero(), vdot2(), and vdot3().
crespsp()
subroutine crespsp (real, dimension (lx1*ly1*lz1,lelv) respr)
Definition at line 99 of file plan4.f.
References add2(), admcol3(), axhelm(), bcdirpr(), cdtp(), chsign(), cmult(), col2(), col_mu_sij(), comp_sij(), faccl2(), faccl3(), invcol2(), invcol3(), invers2(), op_curl(), opadd2cm(), opcolv(), opdssum(), opgrad(), opsub2(), ortho(), rzero(), scale(), and sub2().
cresvsp()
subroutine cresvsp (real, dimension(lx1,ly1,lz1,lelv) resv1, real, dimension(lx1,ly1,lz1,lelv) resv2, real, dimension(lx1,ly1,lz1,lelv) resv3, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2)
Definition at line 264 of file plan4.f.
References add2s1(), col2(), col3(), opadd2(), opchsgn(), opgrad(), ophx(), opsub2(), scale(), and sethlm().
cresvsp_weak()
subroutine cresvsp_weak (real, dimension(lx1,ly1,lz1,lelv) resv1, real, dimension(lx1,ly1,lz1,lelv) resv2, real, dimension(lx1,ly1,lz1,lelv) resv3, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2)
Definition at line 308 of file plan4.f.
References cdtp(), cmult(), col2(), col3(), opadd2(), opchsgn(), opgrad(), ophx(), oprzero(), opsub2(), scale(), sethlm(), and sub2().
op_curl()
subroutine op_curl (real, dimension(1) w1, real, dimension(1) w2, real, dimension(1) w3, real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, logical ifavg, real, dimension(1) work1, real, dimension(1) work2)
Definition at line 368 of file plan4.f.
References add2(), col2(), copy(), dudxyz(), mxm(), opcolv(), opdssum(), rzero(), and sub3().
opadd2cm()
subroutine opadd2cm (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real c)
Definition at line 438 of file plan4.f.
plan4()
subroutine plan4 (igeom)
Definition at line 2 of file plan4.f.
References add2(), bcdirvc(), bcneutr(), copy(), crespsp(), cresvsp(), cresvsp_weak(), ctolspl(), dnekclock(), hsolve(), invers2(), lagvel(), makef(), opadd2(), opcolv(), ophinv(), ortho(), rzero(), and sumab().
printdiverr()
subroutine printdiverr
Definition at line 651 of file plan4.f.
References col2(), col3(), dssum(), glsum(), opdiv(), and sub3().
qthermal()
subroutine qthermal
Definition at line 636 of file plan4.f.
References rzero().
redo_split_vis()
subroutine redo_split_vis
Definition at line 476 of file plan4.f.
References add2().
split_vis()
subroutine split_vis
Definition at line 458 of file plan4.f.
References cadd2(), and cfill().
sumab()
subroutine sumab (v, vv, real, dimension(lx1*ly1*lz1*lelv,*) vvlag, ntot, real, dimension(*) ab_, nab_)
Definition at line 525 of file plan4.f.
References add2s2(), and add3s2().
userqtl_scig()
subroutine userqtl_scig
Definition at line 544 of file plan4.f.
References add2(), add2s2(), add3s2(), cadd(), cmult(), col2(), col3(), copy(), dssum(), glcflux(), glsum(), invcol2(), invcol3(), makeuq(), opcolv(), opdiv(), opdssum(), opgrad(), and rone().