KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/experimental/rans_komg.f File Reference
rans_komg.f File Reference
Functions/Subroutines
real function rans_komg_mut (ix, iy, iz, iel)
real function rans_komg_mutsk (ix, iy, iz, iel)
real function rans_komg_mutso (ix, iy, iz, iel)
subroutine rans_komg_getcoeffs (coeffs_in)
real function rans_komg_ksrc (ix, iy, iz, iel)
real function rans_komg_omgsrc (ix, iy, iz, iel)
subroutine rans_komg_stndrd_compute
subroutine rans_komg_lowre_compute
subroutine rans_komgsst_stndrd_compute
subroutine rans_komgsst_lowre_compute
subroutine rans_komg_stndrd_compute_noreg
subroutine rans_komg_init (ifld_k_in, ifld_omega_in, ifcoeffs, coeffs_in, wall_id, ywd_in, model_id)
subroutine rans_komg_omegabase
subroutine rans_komg_set_defaultcoeffs
subroutine rans_komgsst_set_defaultcoeffs
subroutine rans_komg_stndrd_eddy
subroutine rans_komg_lowre_eddy
subroutine rans_komgsst_stndrd_eddy
subroutine rans_komgsst_lowre_eddy
subroutine rans_komg_stndrd_eddy_noreg
subroutine comp_stom (St_mag2, Om_mag2, OiOjSk, DivQ)
subroutine comp_sij_oij (sij, oij, nij, u, v, w, iflmc, ifdss)
subroutine dssum_sij_oij (sij, oij, nij)
subroutine comp_sij_oij_mag2 (sij, oij, nij, St_mag2, Om_mag2, OiOjSk)
Function/Subroutine Documentation
comp_sij_oij()
subroutine comp_sij_oij (real, dimension(lx1*ly1*lz1,nij,lelv) sij, real, dimension(lx1*ly1*lz1,lelv,3) oij, nij, real, dimension (lx1*ly1*lz1,lelv) u, real, dimension (lx1*ly1*lz1,lelv) v, real, dimension (lx1*ly1*lz1,lelv) w, logical iflmc, logical ifdss)
Definition at line 2682 of file rans_komg.f.
References dssum_sij_oij(), local_grad2(), local_grad3(), and setaxdy().
comp_sij_oij_mag2()
subroutine comp_sij_oij_mag2 (real, dimension(lx1*ly1*lz1,nij,lelv) sij, real, dimension(lx1*ly1*lz1,lelv,3) oij, nij, real, dimension(lx1*ly1*lz1,lelv) St_mag2, real, dimension(lx1*ly1*lz1,lelv) Om_mag2, real, dimension (lx1*ly1*lz1,lelv) OiOjSk)
Definition at line 2944 of file rans_komg.f.
References add2s2(), add3(), add4(), addcol3(), addcol4(), cmult(), col3(), col4(), rzero(), and subcol4().
comp_stom()
subroutine comp_stom (real, dimension(lx1*ly1*lz1,lelv) St_mag2, real, dimension(lx1*ly1*lz1,lelv) Om_mag2, real, dimension (lx1*ly1*lz1,lelv) OiOjSk, real, dimension (lx1*ly1*lz1,lelv) DivQ)
Definition at line 2637 of file rans_komg.f.
References add2(), add3(), cmult(), comp_sij_oij(), and comp_sij_oij_mag2().
dssum_sij_oij()
subroutine dssum_sij_oij (real, dimension(lx1*ly1*lz1,nij,lelv) sij, real, dimension(lx1*ly1*lz1,lelv,3) oij, nij)
Definition at line 2874 of file rans_komg.f.
References col2(), copy(), dssum(), opcolv(), and opdssum().
rans_komg_getcoeffs()
subroutine rans_komg_getcoeffs (real, dimension(1) coeffs_in)
Definition at line 44 of file rans_komg.f.
rans_komg_init()
subroutine rans_komg_init (ifld_k_in, ifld_omega_in, logical ifcoeffs, real, dimension(1) coeffs_in, integer wall_id, real, dimension(1) ywd_in, model_id)
Definition at line 1556 of file rans_komg.f.
References cheap_dist(), copy(), distf(), exitt(), exitti(), rans_komg_omegabase(), rans_komg_set_defaultcoeffs(), and rans_komgsst_set_defaultcoeffs().
rans_komg_ksrc()
real function rans_komg_ksrc (ix, iy, iz, iel)
Definition at line 58 of file rans_komg.f.
References rans_komg_lowre_compute(), rans_komg_stndrd_compute(), rans_komg_stndrd_compute_noreg(), rans_komgsst_lowre_compute(), and rans_komgsst_stndrd_compute().
rans_komg_lowre_compute()
subroutine rans_komg_lowre_compute
Definition at line 389 of file rans_komg.f.
References add2(), add3(), addcol3(), admcol3(), cmult(), col2(), col3(), col4(), comp_stom(), copy(), glmin(), gradm11(), iglsum(), invcol2(), and subcol3().
rans_komg_lowre_eddy()
subroutine rans_komg_lowre_eddy
Definition at line 2001 of file rans_komg.f.
References glmin(), and iglsum().
rans_komg_mut()
real function rans_komg_mut (ix, iy, iz, iel)
Definition at line 1 of file rans_komg.f.
References rans_komg_lowre_eddy(), rans_komg_stndrd_eddy(), rans_komg_stndrd_eddy_noreg(), rans_komgsst_lowre_eddy(), and rans_komgsst_stndrd_eddy().
rans_komg_mutsk()
real function rans_komg_mutsk (ix, iy, iz, iel)
Definition at line 24 of file rans_komg.f.
rans_komg_mutso()
real function rans_komg_mutso (ix, iy, iz, iel)
Definition at line 34 of file rans_komg.f.
rans_komg_omegabase()
subroutine rans_komg_omegabase
Definition at line 1656 of file rans_komg.f.
References glmin(), gradm1(), opcolv(), opdssum(), rone(), and rzero().
rans_komg_omgsrc()
real function rans_komg_omgsrc (ix, iy, iz, iel)
Definition at line 83 of file rans_komg.f.
References rans_komg_lowre_compute(), rans_komg_stndrd_compute(), rans_komg_stndrd_compute_noreg(), rans_komgsst_lowre_compute(), and rans_komgsst_stndrd_compute().
rans_komg_set_defaultcoeffs()
subroutine rans_komg_set_defaultcoeffs
Definition at line 1739 of file rans_komg.f.
rans_komg_stndrd_compute()
subroutine rans_komg_stndrd_compute
Definition at line 108 of file rans_komg.f.
References add2(), add3(), addcol3(), admcol3(), cmult(), col2(), col3(), col4(), comp_stom(), copy(), glmin(), gradm11(), iglsum(), invcol2(), and subcol3().
rans_komg_stndrd_compute_noreg()
subroutine rans_komg_stndrd_compute_noreg
Definition at line 1329 of file rans_komg.f.
References comp_stom(), copy(), glmin(), gradm11(), and iglsum().
rans_komg_stndrd_eddy()
subroutine rans_komg_stndrd_eddy
Definition at line 1879 of file rans_komg.f.
References glmin(), and iglsum().
rans_komg_stndrd_eddy_noreg()
subroutine rans_komg_stndrd_eddy_noreg
Definition at line 2516 of file rans_komg.f.
References glmin(), and iglsum().
rans_komgsst_lowre_compute()
subroutine rans_komgsst_lowre_compute
Definition at line 980 of file rans_komg.f.
References add2(), add3(), addcol3(), admcol3(), cmult(), col2(), col3(), col4(), comp_stom(), copy(), glmin(), gradm11(), iglsum(), invcol2(), and subcol3().
rans_komgsst_lowre_eddy()
subroutine rans_komgsst_lowre_eddy
Definition at line 2317 of file rans_komg.f.
References comp_stom(), glmin(), gradm11(), and iglsum().
rans_komgsst_set_defaultcoeffs()
subroutine rans_komgsst_set_defaultcoeffs
Definition at line 1802 of file rans_komg.f.
rans_komgsst_stndrd_compute()
subroutine rans_komgsst_stndrd_compute
Definition at line 676 of file rans_komg.f.
References add2(), add3(), addcol3(), admcol3(), cmult(), col2(), col3(), col4(), comp_stom(), copy(), glmin(), gradm11(), iglsum(), invcol2(), and subcol3().
rans_komgsst_stndrd_eddy()
subroutine rans_komgsst_stndrd_eddy
Definition at line 2125 of file rans_komg.f.
References comp_stom(), glmin(), gradm11(), and iglsum().