KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/reader_re2.f File Reference
reader_re2.f File Reference
Functions/Subroutines
subroutine read_re2_data (ifbswap)
subroutine readp_re2_mesh (ifbswap, ifdistri)
subroutine readp_re2_curve (ifbswap)
subroutine readp_re2_bc (cbl, bl, ifbswap)
subroutine buf_to_xyz (buf, e, ifbswap, ierr)
subroutine buf_to_curve (buf)
subroutine buf_to_bc (cbl, bl, buf)
subroutine bin_rd1_mesh (ifbswap)
subroutine bin_rd1_curve (ifbswap)
subroutine bin_rd1_bc (cbl, bl, ifbswap)
subroutine buf_close_outv
subroutine buf_close_out
subroutine read_re2_hdr (ifbswap, ifverbose)
Function/Subroutine Documentation
bin_rd1_bc()
subroutine bin_rd1_bc (character*3, dimension(6,lelt) cbl, real, dimension(5,6,lelt) bl, logical ifbswap)
Definition at line 625 of file reader_re2.f.
References buf_close_outv(), buf_to_bc(), byte_read, byte_reverse, byte_reverse8, copyi4(), crecv(), csend(), err_chk(), exitt(), gllnid(), and nekgsync().
bin_rd1_curve()
subroutine bin_rd1_curve (logical ifbswap)
Definition at line 539 of file reader_re2.f.
References buf_close_out(), buf_to_curve(), byte_read, byte_reverse, byte_reverse8, copyi4(), crecv(), csend(), err_chk(), exitt(), gllnid(), and nekgsync().
bin_rd1_mesh()
subroutine bin_rd1_mesh (logical ifbswap)
Definition at line 469 of file reader_re2.f.
References buf_to_xyz(), byte_read, crecv(), csend(), err_chk(), exitt(), gllel(), gllnid(), and nekgsync().
buf_close_out()
subroutine buf_close_out
Definition at line 750 of file reader_re2.f.
References csend().
buf_close_outv()
subroutine buf_close_outv
Definition at line 728 of file reader_re2.f.
References csend().
buf_to_bc()
subroutine buf_to_bc (character*3, dimension(6,lelt) cbl, real, dimension(5,6,lelt) bl, integer, dimension(30) buf)
Definition at line 427 of file reader_re2.f.
References chcopy(), copy(), copy4r(), copyi4(), and gllel().
buf_to_curve()
subroutine buf_to_curve (integer, dimension(30) buf)
Definition at line 397 of file reader_re2.f.
References chcopy(), copy(), copy4r(), copyi4(), and gllel().
buf_to_xyz()
subroutine buf_to_xyz (integer, dimension(0:49) buf, integer e, logical ifbswap, ierr)
Definition at line 354 of file reader_re2.f.
References byte_reverse, byte_reverse8, copy(), copy4r(), and copyi4().
read_re2_data()
subroutine read_re2_data (logical ifbswap)
Definition at line 2 of file reader_re2.f.
References bin_rd1_bc(), bin_rd1_curve(), bin_rd1_mesh(), blank(), byte_close, byte_close_mpi(), byte_open, byte_open_mpi(), byte_read, dnekclock_sync(), err_chk(), readp_re2_bc(), readp_re2_curve(), readp_re2_mesh(), and rzero().
read_re2_hdr()
subroutine read_re2_hdr (logical ifbswap, logical ifverbose)
Definition at line 771 of file reader_re2.f.
References bcast(), byte_close, byte_open, byte_read, chcopy(), err_chk(), exitti(), indx2(), and izero().
readp_re2_bc()
subroutine readp_re2_bc (character*3, dimension(6,lelt) cbl, real, dimension (5,6,lelt) bl, logical ifbswap)
Definition at line 246 of file reader_re2.f.
References buf_to_bc(), byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), copy(), copyi4(), err_chk(), gllnid(), icopy(), and igl_running_sum().
readp_re2_curve()
subroutine readp_re2_curve (logical ifbswap)
Definition at line 145 of file reader_re2.f.
References buf_to_curve(), byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), copy(), copyi4(), err_chk(), gllnid(), icopy(), and igl_running_sum().
readp_re2_mesh()
subroutine readp_re2_mesh (logical ifbswap, logical ifdistri)
Definition at line 68 of file reader_re2.f.
References buf_to_xyz(), byte_read_mpi(), byte_set_view(), err_chk(), gllel(), gllnid(), icopy(), and igl_running_sum().