KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/3rd_party/visit.f File Reference
visit.f File Reference
Functions/Subroutines
subroutine visit_init
subroutine simulationarguments ()
integer function processvisitcommand ()
subroutine visit_check ()
subroutine visit_end ()
subroutine visitcommandcallback (cmd, lcmd, args, largs)
integer function visitbroadcastintfunction (value, sender)
integer function visitbroadcaststringfunction (str, lstr, sender)
subroutine visitslaveprocesscallback ()
integer function visitactivatetimestep ()
integer function visitgetmetadata ()
integer function visitgetmesh (domain, name, lname)
integer function visitgetmaterial (domain, name, lname)
integer function visitgetvariable (gdomain, name, lname)
integer function visitgetcurve (handle, name, lname)
integer function visitgetdomainlist ()
integer function visitgetdomainbounds (name, lname)
integer function visitgetdomainnesting (name, lname)
integer function visitgetmixedvariable (domain, name, lname)
Function/Subroutine Documentation
processvisitcommand()
integer function processvisitcommand
Definition at line 103 of file visit.f.
References mpi_bcast().
simulationarguments()
subroutine simulationarguments
Definition at line 71 of file visit.f.
visit_check()
subroutine visit_check
Definition at line 153 of file visit.f.
References mpi_bcast().
visit_end()
subroutine visit_end
Definition at line 239 of file visit.f.
References visit_check().
visit_init()
subroutine visit_init
Definition at line 15 of file visit.f.
References mpi_comm_rank(), mpi_comm_size(), and simulationarguments().
visitactivatetimestep()
integer function visitactivatetimestep
Definition at line 344 of file visit.f.
visitbroadcastintfunction()
integer function visitbroadcastintfunction (value, integer, value sender)
Definition at line 309 of file visit.f.
References mpi_bcast().
visitbroadcaststringfunction()
integer function visitbroadcaststringfunction (character*8 str, integer lstr, integer sender)
Definition at line 320 of file visit.f.
References mpi_bcast().
visitcommandcallback()
subroutine visitcommandcallback (character*8 cmd, integer lcmd, character*8 args, integer largs)
Definition at line 280 of file visit.f.
References exitt().
visitgetcurve()
integer function visitgetcurve (integer handle, character*8 name, integer lname)
Definition at line 673 of file visit.f.
visitgetdomainbounds()
integer function visitgetdomainbounds (character*8 name, integer lname)
Definition at line 717 of file visit.f.
visitgetdomainlist()
integer function visitgetdomainlist
Definition at line 685 of file visit.f.
visitgetdomainnesting()
integer function visitgetdomainnesting (character*8 name, integer lname)
Definition at line 729 of file visit.f.
visitgetmaterial()
integer function visitgetmaterial (integer domain, character*8 name, integer lname)
Definition at line 600 of file visit.f.
visitgetmesh()
integer function visitgetmesh (integer domain, character*8 name, integer lname)
Definition at line 550 of file visit.f.
References gllel().
visitgetmetadata()
integer function visitgetmetadata
Definition at line 355 of file visit.f.
visitgetmixedvariable()
integer function visitgetmixedvariable (integer domain, character*8 name, integer lname)
Definition at line 742 of file visit.f.
visitgetvariable()
integer function visitgetvariable (integer gdomain, character*8 name, integer lname)
Definition at line 612 of file visit.f.
References gllel().
visitslaveprocesscallback()
subroutine visitslaveprocesscallback
Definition at line 332 of file visit.f.
References mpi_bcast().