KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/zgecon.f File Reference
zgecon.f File Reference
Functions/Subroutines
subroutine zgecon (NORM, N, A, LDA, ANORM, RCOND, WORK, RWORK, INFO)
Function/Subroutine Documentation
zgecon()
subroutine zgecon (character NORM, integer N, complex*16, dimension(lda, *) A, integer LDA, double precision ANORM, double precision RCOND, complex*16, dimension(*) WORK, double precision, dimension(*) RWORK, integer INFO)
Definition at line 1 of file zgecon.f.
References xerbla(), zdrscl(), zlacon(), and zlatrs().