KTH framework for Nek5000 toolboxes; testing version: Nek5000/3rd_party/blasLapack/zlatrs.f File Reference
zlatrs.f File Reference
Functions/Subroutines
subroutine zlatrs (UPLO, TRANS, DIAG, NORMIN, N, A, LDA, X, SCALE, CNORM, INFO)
Function/Subroutine Documentation
zlatrs()
subroutine zlatrs (character UPLO, character TRANS, character DIAG, character NORMIN, integer N, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, double precision SCALE, double precision, dimension(*) CNORM, integer INFO)
Definition at line 1 of file zlatrs.f.
References dlabad(), dscal(), xerbla(), zaxpy(), zdscal(), and ztrsv().